// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/transaction/create_transaction_response.proto

package common.request;

public final class CreateTransactionResponseProtos {
  private CreateTransactionResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transaction_CreateTransactionResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transaction_CreateTransactionResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6requests/transaction/create_transactio" +
      "n_response.proto\022\013transaction\032$models/tr" +
      "ansaction/transaction.proto\0325requests/tr" +
      "ansaction/create_transaction_request.pro" +
      "to\"\324\001\n\036CreateTransactionResponseProto\022\024\n" +
      "\014object_class\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022N\n\032" +
      "create_transaction_request\030\024 \001(\0132*.trans" +
      "action.CreateTransactionRequestProto\022;\n\024" +
      "transaction_response\030\036 \001(\0132\035.transaction" +
      ".TransactionProtoB3\n\016common.requestB\037Cre" +
      "ateTransactionResponseProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.models.transaction.TransactionProtos.getDescriptor(),
          common.request.CreateTransactionRequestProtos.getDescriptor(),
        });
    internal_static_transaction_CreateTransactionResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transaction_CreateTransactionResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transaction_CreateTransactionResponseProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "CreateTransactionRequest", "TransactionResponse", });
    common.models.transaction.TransactionProtos.getDescriptor();
    common.request.CreateTransactionRequestProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
