// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/portfolio/portfolio_request.proto

package common.request;

/**
 * Protobuf type {@code portfolio.PortfolioRequestProto}
 */
public final class PortfolioRequestProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:portfolio.PortfolioRequestProto)
    PortfolioRequestProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PortfolioRequestProto.newBuilder() to construct.
  private PortfolioRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PortfolioRequestProto() {
    objectClass_ = "";
    version_ = "";
    operationType_ = 0;
    uuids_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PortfolioRequestProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PortfolioRequestProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            objectClass_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            operationType_ = rawValue;
            break;
          }
          case 162: {
            common.models.portfolio.PortfolioProto.Builder subBuilder = null;
            if (createPortfolioInput_ != null) {
              subBuilder = createPortfolioInput_.toBuilder();
            }
            createPortfolioInput_ = input.readMessage(common.models.portfolio.PortfolioProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createPortfolioInput_);
              createPortfolioInput_ = subBuilder.buildPartial();
            }

            break;
          }
          case 170: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              uuids_ = new java.util.ArrayList<common.models.protoUtils.Uuid.UUIDProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            uuids_.add(
                input.readMessage(common.models.protoUtils.Uuid.UUIDProto.parser(), extensionRegistry));
            break;
          }
          case 178: {
            common.models.position.PositionFilterProto.Builder subBuilder = null;
            if (searchPortfolioInput_ != null) {
              subBuilder = searchPortfolioInput_.toBuilder();
            }
            searchPortfolioInput_ = input.readMessage(common.models.position.PositionFilterProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(searchPortfolioInput_);
              searchPortfolioInput_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        uuids_ = java.util.Collections.unmodifiableList(uuids_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return common.request.PortfolioRequestProtos.internal_static_portfolio_PortfolioRequestProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return common.request.PortfolioRequestProtos.internal_static_portfolio_PortfolioRequestProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            common.request.PortfolioRequestProto.class, common.request.PortfolioRequestProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectClass_;
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_TYPE_FIELD_NUMBER = 10;
  private int operationType_;
  /**
   * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
   * @return The enum numeric value on the wire for operationType.
   */
  @java.lang.Override public int getOperationTypeValue() {
    return operationType_;
  }
  /**
   * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
   * @return The operationType.
   */
  @java.lang.Override public common.request.util.RequestOperationTypeProto getOperationType() {
    @SuppressWarnings("deprecation")
    common.request.util.RequestOperationTypeProto result = common.request.util.RequestOperationTypeProto.valueOf(operationType_);
    return result == null ? common.request.util.RequestOperationTypeProto.UNRECOGNIZED : result;
  }

  public static final int CREATE_PORTFOLIO_INPUT_FIELD_NUMBER = 20;
  private common.models.portfolio.PortfolioProto createPortfolioInput_;
  /**
   * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
   * @return Whether the createPortfolioInput field is set.
   */
  @java.lang.Override
  public boolean hasCreatePortfolioInput() {
    return createPortfolioInput_ != null;
  }
  /**
   * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
   * @return The createPortfolioInput.
   */
  @java.lang.Override
  public common.models.portfolio.PortfolioProto getCreatePortfolioInput() {
    return createPortfolioInput_ == null ? common.models.portfolio.PortfolioProto.getDefaultInstance() : createPortfolioInput_;
  }
  /**
   * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
   */
  @java.lang.Override
  public common.models.portfolio.PortfolioProtoOrBuilder getCreatePortfolioInputOrBuilder() {
    return getCreatePortfolioInput();
  }

  public static final int UUIDS_FIELD_NUMBER = 21;
  private java.util.List<common.models.protoUtils.Uuid.UUIDProto> uuids_;
  /**
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  @java.lang.Override
  public java.util.List<common.models.protoUtils.Uuid.UUIDProto> getUuidsList() {
    return uuids_;
  }
  /**
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  @java.lang.Override
  public java.util.List<? extends common.models.protoUtils.Uuid.UUIDProtoOrBuilder> 
      getUuidsOrBuilderList() {
    return uuids_;
  }
  /**
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  @java.lang.Override
  public int getUuidsCount() {
    return uuids_.size();
  }
  /**
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  @java.lang.Override
  public common.models.protoUtils.Uuid.UUIDProto getUuids(int index) {
    return uuids_.get(index);
  }
  /**
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  @java.lang.Override
  public common.models.protoUtils.Uuid.UUIDProtoOrBuilder getUuidsOrBuilder(
      int index) {
    return uuids_.get(index);
  }

  public static final int SEARCH_PORTFOLIO_INPUT_FIELD_NUMBER = 22;
  private common.models.position.PositionFilterProto searchPortfolioInput_;
  /**
   * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
   * @return Whether the searchPortfolioInput field is set.
   */
  @java.lang.Override
  public boolean hasSearchPortfolioInput() {
    return searchPortfolioInput_ != null;
  }
  /**
   * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
   * @return The searchPortfolioInput.
   */
  @java.lang.Override
  public common.models.position.PositionFilterProto getSearchPortfolioInput() {
    return searchPortfolioInput_ == null ? common.models.position.PositionFilterProto.getDefaultInstance() : searchPortfolioInput_;
  }
  /**
   * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
   */
  @java.lang.Override
  public common.models.position.PositionFilterProtoOrBuilder getSearchPortfolioInputOrBuilder() {
    return getSearchPortfolioInput();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getObjectClassBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (operationType_ != common.request.util.RequestOperationTypeProto.UNKNOWN_OPERATION.getNumber()) {
      output.writeEnum(10, operationType_);
    }
    if (createPortfolioInput_ != null) {
      output.writeMessage(20, getCreatePortfolioInput());
    }
    for (int i = 0; i < uuids_.size(); i++) {
      output.writeMessage(21, uuids_.get(i));
    }
    if (searchPortfolioInput_ != null) {
      output.writeMessage(22, getSearchPortfolioInput());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getObjectClassBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (operationType_ != common.request.util.RequestOperationTypeProto.UNKNOWN_OPERATION.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, operationType_);
    }
    if (createPortfolioInput_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getCreatePortfolioInput());
    }
    for (int i = 0; i < uuids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, uuids_.get(i));
    }
    if (searchPortfolioInput_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getSearchPortfolioInput());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof common.request.PortfolioRequestProto)) {
      return super.equals(obj);
    }
    common.request.PortfolioRequestProto other = (common.request.PortfolioRequestProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (operationType_ != other.operationType_) return false;
    if (hasCreatePortfolioInput() != other.hasCreatePortfolioInput()) return false;
    if (hasCreatePortfolioInput()) {
      if (!getCreatePortfolioInput()
          .equals(other.getCreatePortfolioInput())) return false;
    }
    if (!getUuidsList()
        .equals(other.getUuidsList())) return false;
    if (hasSearchPortfolioInput() != other.hasSearchPortfolioInput()) return false;
    if (hasSearchPortfolioInput()) {
      if (!getSearchPortfolioInput()
          .equals(other.getSearchPortfolioInput())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + OPERATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + operationType_;
    if (hasCreatePortfolioInput()) {
      hash = (37 * hash) + CREATE_PORTFOLIO_INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatePortfolioInput().hashCode();
    }
    if (getUuidsCount() > 0) {
      hash = (37 * hash) + UUIDS_FIELD_NUMBER;
      hash = (53 * hash) + getUuidsList().hashCode();
    }
    if (hasSearchPortfolioInput()) {
      hash = (37 * hash) + SEARCH_PORTFOLIO_INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getSearchPortfolioInput().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static common.request.PortfolioRequestProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.PortfolioRequestProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.PortfolioRequestProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static common.request.PortfolioRequestProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static common.request.PortfolioRequestProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static common.request.PortfolioRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(common.request.PortfolioRequestProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code portfolio.PortfolioRequestProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:portfolio.PortfolioRequestProto)
      common.request.PortfolioRequestProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.request.PortfolioRequestProtos.internal_static_portfolio_PortfolioRequestProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.request.PortfolioRequestProtos.internal_static_portfolio_PortfolioRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common.request.PortfolioRequestProto.class, common.request.PortfolioRequestProto.Builder.class);
    }

    // Construct using common.request.PortfolioRequestProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUuidsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectClass_ = "";

      version_ = "";

      operationType_ = 0;

      if (createPortfolioInputBuilder_ == null) {
        createPortfolioInput_ = null;
      } else {
        createPortfolioInput_ = null;
        createPortfolioInputBuilder_ = null;
      }
      if (uuidsBuilder_ == null) {
        uuids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        uuidsBuilder_.clear();
      }
      if (searchPortfolioInputBuilder_ == null) {
        searchPortfolioInput_ = null;
      } else {
        searchPortfolioInput_ = null;
        searchPortfolioInputBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return common.request.PortfolioRequestProtos.internal_static_portfolio_PortfolioRequestProto_descriptor;
    }

    @java.lang.Override
    public common.request.PortfolioRequestProto getDefaultInstanceForType() {
      return common.request.PortfolioRequestProto.getDefaultInstance();
    }

    @java.lang.Override
    public common.request.PortfolioRequestProto build() {
      common.request.PortfolioRequestProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public common.request.PortfolioRequestProto buildPartial() {
      common.request.PortfolioRequestProto result = new common.request.PortfolioRequestProto(this);
      int from_bitField0_ = bitField0_;
      result.objectClass_ = objectClass_;
      result.version_ = version_;
      result.operationType_ = operationType_;
      if (createPortfolioInputBuilder_ == null) {
        result.createPortfolioInput_ = createPortfolioInput_;
      } else {
        result.createPortfolioInput_ = createPortfolioInputBuilder_.build();
      }
      if (uuidsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          uuids_ = java.util.Collections.unmodifiableList(uuids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uuids_ = uuids_;
      } else {
        result.uuids_ = uuidsBuilder_.build();
      }
      if (searchPortfolioInputBuilder_ == null) {
        result.searchPortfolioInput_ = searchPortfolioInput_;
      } else {
        result.searchPortfolioInput_ = searchPortfolioInputBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof common.request.PortfolioRequestProto) {
        return mergeFrom((common.request.PortfolioRequestProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(common.request.PortfolioRequestProto other) {
      if (other == common.request.PortfolioRequestProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.operationType_ != 0) {
        setOperationTypeValue(other.getOperationTypeValue());
      }
      if (other.hasCreatePortfolioInput()) {
        mergeCreatePortfolioInput(other.getCreatePortfolioInput());
      }
      if (uuidsBuilder_ == null) {
        if (!other.uuids_.isEmpty()) {
          if (uuids_.isEmpty()) {
            uuids_ = other.uuids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUuidsIsMutable();
            uuids_.addAll(other.uuids_);
          }
          onChanged();
        }
      } else {
        if (!other.uuids_.isEmpty()) {
          if (uuidsBuilder_.isEmpty()) {
            uuidsBuilder_.dispose();
            uuidsBuilder_ = null;
            uuids_ = other.uuids_;
            bitField0_ = (bitField0_ & ~0x00000001);
            uuidsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUuidsFieldBuilder() : null;
          } else {
            uuidsBuilder_.addAllMessages(other.uuids_);
          }
        }
      }
      if (other.hasSearchPortfolioInput()) {
        mergeSearchPortfolioInput(other.getSearchPortfolioInput());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      common.request.PortfolioRequestProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (common.request.PortfolioRequestProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      
      objectClass_ = getDefaultInstance().getObjectClass();
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private int operationType_ = 0;
    /**
     * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
     * @return The enum numeric value on the wire for operationType.
     */
    @java.lang.Override public int getOperationTypeValue() {
      return operationType_;
    }
    /**
     * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
     * @param value The enum numeric value on the wire for operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationTypeValue(int value) {
      
      operationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
     * @return The operationType.
     */
    @java.lang.Override
    public common.request.util.RequestOperationTypeProto getOperationType() {
      @SuppressWarnings("deprecation")
      common.request.util.RequestOperationTypeProto result = common.request.util.RequestOperationTypeProto.valueOf(operationType_);
      return result == null ? common.request.util.RequestOperationTypeProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
     * @param value The operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationType(common.request.util.RequestOperationTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operationType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.util.RequestOperationTypeProto operation_type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationType() {
      
      operationType_ = 0;
      onChanged();
      return this;
    }

    private common.models.portfolio.PortfolioProto createPortfolioInput_;
    private com.google.protobuf.SingleFieldBuilderV3<
        common.models.portfolio.PortfolioProto, common.models.portfolio.PortfolioProto.Builder, common.models.portfolio.PortfolioProtoOrBuilder> createPortfolioInputBuilder_;
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     * @return Whether the createPortfolioInput field is set.
     */
    public boolean hasCreatePortfolioInput() {
      return createPortfolioInputBuilder_ != null || createPortfolioInput_ != null;
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     * @return The createPortfolioInput.
     */
    public common.models.portfolio.PortfolioProto getCreatePortfolioInput() {
      if (createPortfolioInputBuilder_ == null) {
        return createPortfolioInput_ == null ? common.models.portfolio.PortfolioProto.getDefaultInstance() : createPortfolioInput_;
      } else {
        return createPortfolioInputBuilder_.getMessage();
      }
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public Builder setCreatePortfolioInput(common.models.portfolio.PortfolioProto value) {
      if (createPortfolioInputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createPortfolioInput_ = value;
        onChanged();
      } else {
        createPortfolioInputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public Builder setCreatePortfolioInput(
        common.models.portfolio.PortfolioProto.Builder builderForValue) {
      if (createPortfolioInputBuilder_ == null) {
        createPortfolioInput_ = builderForValue.build();
        onChanged();
      } else {
        createPortfolioInputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public Builder mergeCreatePortfolioInput(common.models.portfolio.PortfolioProto value) {
      if (createPortfolioInputBuilder_ == null) {
        if (createPortfolioInput_ != null) {
          createPortfolioInput_ =
            common.models.portfolio.PortfolioProto.newBuilder(createPortfolioInput_).mergeFrom(value).buildPartial();
        } else {
          createPortfolioInput_ = value;
        }
        onChanged();
      } else {
        createPortfolioInputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public Builder clearCreatePortfolioInput() {
      if (createPortfolioInputBuilder_ == null) {
        createPortfolioInput_ = null;
        onChanged();
      } else {
        createPortfolioInput_ = null;
        createPortfolioInputBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public common.models.portfolio.PortfolioProto.Builder getCreatePortfolioInputBuilder() {
      
      onChanged();
      return getCreatePortfolioInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    public common.models.portfolio.PortfolioProtoOrBuilder getCreatePortfolioInputOrBuilder() {
      if (createPortfolioInputBuilder_ != null) {
        return createPortfolioInputBuilder_.getMessageOrBuilder();
      } else {
        return createPortfolioInput_ == null ?
            common.models.portfolio.PortfolioProto.getDefaultInstance() : createPortfolioInput_;
      }
    }
    /**
     * <code>.portfolio.PortfolioProto create_portfolio_input = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        common.models.portfolio.PortfolioProto, common.models.portfolio.PortfolioProto.Builder, common.models.portfolio.PortfolioProtoOrBuilder> 
        getCreatePortfolioInputFieldBuilder() {
      if (createPortfolioInputBuilder_ == null) {
        createPortfolioInputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            common.models.portfolio.PortfolioProto, common.models.portfolio.PortfolioProto.Builder, common.models.portfolio.PortfolioProtoOrBuilder>(
                getCreatePortfolioInput(),
                getParentForChildren(),
                isClean());
        createPortfolioInput_ = null;
      }
      return createPortfolioInputBuilder_;
    }

    private java.util.List<common.models.protoUtils.Uuid.UUIDProto> uuids_ =
      java.util.Collections.emptyList();
    private void ensureUuidsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        uuids_ = new java.util.ArrayList<common.models.protoUtils.Uuid.UUIDProto>(uuids_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        common.models.protoUtils.Uuid.UUIDProto, common.models.protoUtils.Uuid.UUIDProto.Builder, common.models.protoUtils.Uuid.UUIDProtoOrBuilder> uuidsBuilder_;

    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public java.util.List<common.models.protoUtils.Uuid.UUIDProto> getUuidsList() {
      if (uuidsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uuids_);
      } else {
        return uuidsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public int getUuidsCount() {
      if (uuidsBuilder_ == null) {
        return uuids_.size();
      } else {
        return uuidsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public common.models.protoUtils.Uuid.UUIDProto getUuids(int index) {
      if (uuidsBuilder_ == null) {
        return uuids_.get(index);
      } else {
        return uuidsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder setUuids(
        int index, common.models.protoUtils.Uuid.UUIDProto value) {
      if (uuidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUuidsIsMutable();
        uuids_.set(index, value);
        onChanged();
      } else {
        uuidsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder setUuids(
        int index, common.models.protoUtils.Uuid.UUIDProto.Builder builderForValue) {
      if (uuidsBuilder_ == null) {
        ensureUuidsIsMutable();
        uuids_.set(index, builderForValue.build());
        onChanged();
      } else {
        uuidsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder addUuids(common.models.protoUtils.Uuid.UUIDProto value) {
      if (uuidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUuidsIsMutable();
        uuids_.add(value);
        onChanged();
      } else {
        uuidsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder addUuids(
        int index, common.models.protoUtils.Uuid.UUIDProto value) {
      if (uuidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUuidsIsMutable();
        uuids_.add(index, value);
        onChanged();
      } else {
        uuidsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder addUuids(
        common.models.protoUtils.Uuid.UUIDProto.Builder builderForValue) {
      if (uuidsBuilder_ == null) {
        ensureUuidsIsMutable();
        uuids_.add(builderForValue.build());
        onChanged();
      } else {
        uuidsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder addUuids(
        int index, common.models.protoUtils.Uuid.UUIDProto.Builder builderForValue) {
      if (uuidsBuilder_ == null) {
        ensureUuidsIsMutable();
        uuids_.add(index, builderForValue.build());
        onChanged();
      } else {
        uuidsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder addAllUuids(
        java.lang.Iterable<? extends common.models.protoUtils.Uuid.UUIDProto> values) {
      if (uuidsBuilder_ == null) {
        ensureUuidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uuids_);
        onChanged();
      } else {
        uuidsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder clearUuids() {
      if (uuidsBuilder_ == null) {
        uuids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        uuidsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public Builder removeUuids(int index) {
      if (uuidsBuilder_ == null) {
        ensureUuidsIsMutable();
        uuids_.remove(index);
        onChanged();
      } else {
        uuidsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public common.models.protoUtils.Uuid.UUIDProto.Builder getUuidsBuilder(
        int index) {
      return getUuidsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public common.models.protoUtils.Uuid.UUIDProtoOrBuilder getUuidsOrBuilder(
        int index) {
      if (uuidsBuilder_ == null) {
        return uuids_.get(index);  } else {
        return uuidsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public java.util.List<? extends common.models.protoUtils.Uuid.UUIDProtoOrBuilder> 
         getUuidsOrBuilderList() {
      if (uuidsBuilder_ != null) {
        return uuidsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uuids_);
      }
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public common.models.protoUtils.Uuid.UUIDProto.Builder addUuidsBuilder() {
      return getUuidsFieldBuilder().addBuilder(
          common.models.protoUtils.Uuid.UUIDProto.getDefaultInstance());
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public common.models.protoUtils.Uuid.UUIDProto.Builder addUuidsBuilder(
        int index) {
      return getUuidsFieldBuilder().addBuilder(
          index, common.models.protoUtils.Uuid.UUIDProto.getDefaultInstance());
    }
    /**
     * <code>repeated .util.UUIDProto uuids = 21;</code>
     */
    public java.util.List<common.models.protoUtils.Uuid.UUIDProto.Builder> 
         getUuidsBuilderList() {
      return getUuidsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        common.models.protoUtils.Uuid.UUIDProto, common.models.protoUtils.Uuid.UUIDProto.Builder, common.models.protoUtils.Uuid.UUIDProtoOrBuilder> 
        getUuidsFieldBuilder() {
      if (uuidsBuilder_ == null) {
        uuidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            common.models.protoUtils.Uuid.UUIDProto, common.models.protoUtils.Uuid.UUIDProto.Builder, common.models.protoUtils.Uuid.UUIDProtoOrBuilder>(
                uuids_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        uuids_ = null;
      }
      return uuidsBuilder_;
    }

    private common.models.position.PositionFilterProto searchPortfolioInput_;
    private com.google.protobuf.SingleFieldBuilderV3<
        common.models.position.PositionFilterProto, common.models.position.PositionFilterProto.Builder, common.models.position.PositionFilterProtoOrBuilder> searchPortfolioInputBuilder_;
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     * @return Whether the searchPortfolioInput field is set.
     */
    public boolean hasSearchPortfolioInput() {
      return searchPortfolioInputBuilder_ != null || searchPortfolioInput_ != null;
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     * @return The searchPortfolioInput.
     */
    public common.models.position.PositionFilterProto getSearchPortfolioInput() {
      if (searchPortfolioInputBuilder_ == null) {
        return searchPortfolioInput_ == null ? common.models.position.PositionFilterProto.getDefaultInstance() : searchPortfolioInput_;
      } else {
        return searchPortfolioInputBuilder_.getMessage();
      }
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public Builder setSearchPortfolioInput(common.models.position.PositionFilterProto value) {
      if (searchPortfolioInputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        searchPortfolioInput_ = value;
        onChanged();
      } else {
        searchPortfolioInputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public Builder setSearchPortfolioInput(
        common.models.position.PositionFilterProto.Builder builderForValue) {
      if (searchPortfolioInputBuilder_ == null) {
        searchPortfolioInput_ = builderForValue.build();
        onChanged();
      } else {
        searchPortfolioInputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public Builder mergeSearchPortfolioInput(common.models.position.PositionFilterProto value) {
      if (searchPortfolioInputBuilder_ == null) {
        if (searchPortfolioInput_ != null) {
          searchPortfolioInput_ =
            common.models.position.PositionFilterProto.newBuilder(searchPortfolioInput_).mergeFrom(value).buildPartial();
        } else {
          searchPortfolioInput_ = value;
        }
        onChanged();
      } else {
        searchPortfolioInputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public Builder clearSearchPortfolioInput() {
      if (searchPortfolioInputBuilder_ == null) {
        searchPortfolioInput_ = null;
        onChanged();
      } else {
        searchPortfolioInput_ = null;
        searchPortfolioInputBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public common.models.position.PositionFilterProto.Builder getSearchPortfolioInputBuilder() {
      
      onChanged();
      return getSearchPortfolioInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    public common.models.position.PositionFilterProtoOrBuilder getSearchPortfolioInputOrBuilder() {
      if (searchPortfolioInputBuilder_ != null) {
        return searchPortfolioInputBuilder_.getMessageOrBuilder();
      } else {
        return searchPortfolioInput_ == null ?
            common.models.position.PositionFilterProto.getDefaultInstance() : searchPortfolioInput_;
      }
    }
    /**
     * <code>.position.PositionFilterProto search_portfolio_input = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        common.models.position.PositionFilterProto, common.models.position.PositionFilterProto.Builder, common.models.position.PositionFilterProtoOrBuilder> 
        getSearchPortfolioInputFieldBuilder() {
      if (searchPortfolioInputBuilder_ == null) {
        searchPortfolioInputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            common.models.position.PositionFilterProto, common.models.position.PositionFilterProto.Builder, common.models.position.PositionFilterProtoOrBuilder>(
                getSearchPortfolioInput(),
                getParentForChildren(),
                isClean());
        searchPortfolioInput_ = null;
      }
      return searchPortfolioInputBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:portfolio.PortfolioRequestProto)
  }

  // @@protoc_insertion_point(class_scope:portfolio.PortfolioRequestProto)
  private static final common.request.PortfolioRequestProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new common.request.PortfolioRequestProto();
  }

  public static common.request.PortfolioRequestProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PortfolioRequestProto>
      PARSER = new com.google.protobuf.AbstractParser<PortfolioRequestProto>() {
    @java.lang.Override
    public PortfolioRequestProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PortfolioRequestProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PortfolioRequestProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PortfolioRequestProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public common.request.PortfolioRequestProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

