// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/security/query_security_request.proto

package common.request;

public interface QuerySecurityRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.QuerySecurityRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   *The list of UUIDs to return
   * </pre>
   *
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  java.util.List<common.models.protoUtils.Uuid.UUIDProto> 
      getUuidsList();
  /**
   * <pre>
   *The list of UUIDs to return
   * </pre>
   *
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  common.models.protoUtils.Uuid.UUIDProto getUuids(int index);
  /**
   * <pre>
   *The list of UUIDs to return
   * </pre>
   *
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  int getUuidsCount();
  /**
   * <pre>
   *The list of UUIDs to return
   * </pre>
   *
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  java.util.List<? extends common.models.protoUtils.Uuid.UUIDProtoOrBuilder> 
      getUuidsOrBuilderList();
  /**
   * <pre>
   *The list of UUIDs to return
   * </pre>
   *
   * <code>repeated .util.UUIDProto uuids = 21;</code>
   */
  common.models.protoUtils.Uuid.UUIDProtoOrBuilder getUuidsOrBuilder(
      int index);

  /**
   * <pre>
   *A list of position filters that will filter securities that match.
   * </pre>
   *
   * <code>.position.PositionFilterProto search_security_input = 22;</code>
   * @return Whether the searchSecurityInput field is set.
   */
  boolean hasSearchSecurityInput();
  /**
   * <pre>
   *A list of position filters that will filter securities that match.
   * </pre>
   *
   * <code>.position.PositionFilterProto search_security_input = 22;</code>
   * @return The searchSecurityInput.
   */
  common.models.position.PositionFilterProto getSearchSecurityInput();
  /**
   * <pre>
   *A list of position filters that will filter securities that match.
   * </pre>
   *
   * <code>.position.PositionFilterProto search_security_input = 22;</code>
   */
  common.models.position.PositionFilterProtoOrBuilder getSearchSecurityInputOrBuilder();
}
