// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/transaction/transaction_response.proto

package common.request;

/**
 * Protobuf type {@code transaction.TransactionResponseProto}
 */
public final class TransactionResponseProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:transaction.TransactionResponseProto)
    TransactionResponseProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionResponseProto.newBuilder() to construct.
  private TransactionResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionResponseProto() {
    objectClass_ = "";
    version_ = "";
    transactionResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionResponseProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionResponseProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            objectClass_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 162: {
            common.request.TransactionRequestProto.Builder subBuilder = null;
            if (createTransactionRequest_ != null) {
              subBuilder = createTransactionRequest_.toBuilder();
            }
            createTransactionRequest_ = input.readMessage(common.request.TransactionRequestProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createTransactionRequest_);
              createTransactionRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 242: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transactionResponse_ = new java.util.ArrayList<common.models.transaction.TransactionProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            transactionResponse_.add(
                input.readMessage(common.models.transaction.TransactionProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transactionResponse_ = java.util.Collections.unmodifiableList(transactionResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return common.request.TransactionResponseProtos.internal_static_transaction_TransactionResponseProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return common.request.TransactionResponseProtos.internal_static_transaction_TransactionResponseProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            common.request.TransactionResponseProto.class, common.request.TransactionResponseProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectClass_;
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_TRANSACTION_REQUEST_FIELD_NUMBER = 20;
  private common.request.TransactionRequestProto createTransactionRequest_;
  /**
   * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
   * @return Whether the createTransactionRequest field is set.
   */
  @java.lang.Override
  public boolean hasCreateTransactionRequest() {
    return createTransactionRequest_ != null;
  }
  /**
   * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
   * @return The createTransactionRequest.
   */
  @java.lang.Override
  public common.request.TransactionRequestProto getCreateTransactionRequest() {
    return createTransactionRequest_ == null ? common.request.TransactionRequestProto.getDefaultInstance() : createTransactionRequest_;
  }
  /**
   * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
   */
  @java.lang.Override
  public common.request.TransactionRequestProtoOrBuilder getCreateTransactionRequestOrBuilder() {
    return getCreateTransactionRequest();
  }

  public static final int TRANSACTION_RESPONSE_FIELD_NUMBER = 30;
  private java.util.List<common.models.transaction.TransactionProto> transactionResponse_;
  /**
   * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<common.models.transaction.TransactionProto> getTransactionResponseList() {
    return transactionResponse_;
  }
  /**
   * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<? extends common.models.transaction.TransactionProtoOrBuilder> 
      getTransactionResponseOrBuilderList() {
    return transactionResponse_;
  }
  /**
   * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
   */
  @java.lang.Override
  public int getTransactionResponseCount() {
    return transactionResponse_.size();
  }
  /**
   * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
   */
  @java.lang.Override
  public common.models.transaction.TransactionProto getTransactionResponse(int index) {
    return transactionResponse_.get(index);
  }
  /**
   * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
   */
  @java.lang.Override
  public common.models.transaction.TransactionProtoOrBuilder getTransactionResponseOrBuilder(
      int index) {
    return transactionResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getObjectClassBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (createTransactionRequest_ != null) {
      output.writeMessage(20, getCreateTransactionRequest());
    }
    for (int i = 0; i < transactionResponse_.size(); i++) {
      output.writeMessage(30, transactionResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getObjectClassBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (createTransactionRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getCreateTransactionRequest());
    }
    for (int i = 0; i < transactionResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, transactionResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof common.request.TransactionResponseProto)) {
      return super.equals(obj);
    }
    common.request.TransactionResponseProto other = (common.request.TransactionResponseProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasCreateTransactionRequest() != other.hasCreateTransactionRequest()) return false;
    if (hasCreateTransactionRequest()) {
      if (!getCreateTransactionRequest()
          .equals(other.getCreateTransactionRequest())) return false;
    }
    if (!getTransactionResponseList()
        .equals(other.getTransactionResponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasCreateTransactionRequest()) {
      hash = (37 * hash) + CREATE_TRANSACTION_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTransactionRequest().hashCode();
    }
    if (getTransactionResponseCount() > 0) {
      hash = (37 * hash) + TRANSACTION_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static common.request.TransactionResponseProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.TransactionResponseProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.TransactionResponseProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.TransactionResponseProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.TransactionResponseProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static common.request.TransactionResponseProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static common.request.TransactionResponseProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static common.request.TransactionResponseProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static common.request.TransactionResponseProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static common.request.TransactionResponseProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static common.request.TransactionResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static common.request.TransactionResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(common.request.TransactionResponseProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transaction.TransactionResponseProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transaction.TransactionResponseProto)
      common.request.TransactionResponseProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.request.TransactionResponseProtos.internal_static_transaction_TransactionResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.request.TransactionResponseProtos.internal_static_transaction_TransactionResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common.request.TransactionResponseProto.class, common.request.TransactionResponseProto.Builder.class);
    }

    // Construct using common.request.TransactionResponseProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectClass_ = "";

      version_ = "";

      if (createTransactionRequestBuilder_ == null) {
        createTransactionRequest_ = null;
      } else {
        createTransactionRequest_ = null;
        createTransactionRequestBuilder_ = null;
      }
      if (transactionResponseBuilder_ == null) {
        transactionResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transactionResponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return common.request.TransactionResponseProtos.internal_static_transaction_TransactionResponseProto_descriptor;
    }

    @java.lang.Override
    public common.request.TransactionResponseProto getDefaultInstanceForType() {
      return common.request.TransactionResponseProto.getDefaultInstance();
    }

    @java.lang.Override
    public common.request.TransactionResponseProto build() {
      common.request.TransactionResponseProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public common.request.TransactionResponseProto buildPartial() {
      common.request.TransactionResponseProto result = new common.request.TransactionResponseProto(this);
      int from_bitField0_ = bitField0_;
      result.objectClass_ = objectClass_;
      result.version_ = version_;
      if (createTransactionRequestBuilder_ == null) {
        result.createTransactionRequest_ = createTransactionRequest_;
      } else {
        result.createTransactionRequest_ = createTransactionRequestBuilder_.build();
      }
      if (transactionResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transactionResponse_ = java.util.Collections.unmodifiableList(transactionResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactionResponse_ = transactionResponse_;
      } else {
        result.transactionResponse_ = transactionResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof common.request.TransactionResponseProto) {
        return mergeFrom((common.request.TransactionResponseProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(common.request.TransactionResponseProto other) {
      if (other == common.request.TransactionResponseProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasCreateTransactionRequest()) {
        mergeCreateTransactionRequest(other.getCreateTransactionRequest());
      }
      if (transactionResponseBuilder_ == null) {
        if (!other.transactionResponse_.isEmpty()) {
          if (transactionResponse_.isEmpty()) {
            transactionResponse_ = other.transactionResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionResponseIsMutable();
            transactionResponse_.addAll(other.transactionResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.transactionResponse_.isEmpty()) {
          if (transactionResponseBuilder_.isEmpty()) {
            transactionResponseBuilder_.dispose();
            transactionResponseBuilder_ = null;
            transactionResponse_ = other.transactionResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionResponseFieldBuilder() : null;
          } else {
            transactionResponseBuilder_.addAllMessages(other.transactionResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      common.request.TransactionResponseProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (common.request.TransactionResponseProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      
      objectClass_ = getDefaultInstance().getObjectClass();
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private common.request.TransactionRequestProto createTransactionRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        common.request.TransactionRequestProto, common.request.TransactionRequestProto.Builder, common.request.TransactionRequestProtoOrBuilder> createTransactionRequestBuilder_;
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     * @return Whether the createTransactionRequest field is set.
     */
    public boolean hasCreateTransactionRequest() {
      return createTransactionRequestBuilder_ != null || createTransactionRequest_ != null;
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     * @return The createTransactionRequest.
     */
    public common.request.TransactionRequestProto getCreateTransactionRequest() {
      if (createTransactionRequestBuilder_ == null) {
        return createTransactionRequest_ == null ? common.request.TransactionRequestProto.getDefaultInstance() : createTransactionRequest_;
      } else {
        return createTransactionRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public Builder setCreateTransactionRequest(common.request.TransactionRequestProto value) {
      if (createTransactionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTransactionRequest_ = value;
        onChanged();
      } else {
        createTransactionRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public Builder setCreateTransactionRequest(
        common.request.TransactionRequestProto.Builder builderForValue) {
      if (createTransactionRequestBuilder_ == null) {
        createTransactionRequest_ = builderForValue.build();
        onChanged();
      } else {
        createTransactionRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public Builder mergeCreateTransactionRequest(common.request.TransactionRequestProto value) {
      if (createTransactionRequestBuilder_ == null) {
        if (createTransactionRequest_ != null) {
          createTransactionRequest_ =
            common.request.TransactionRequestProto.newBuilder(createTransactionRequest_).mergeFrom(value).buildPartial();
        } else {
          createTransactionRequest_ = value;
        }
        onChanged();
      } else {
        createTransactionRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public Builder clearCreateTransactionRequest() {
      if (createTransactionRequestBuilder_ == null) {
        createTransactionRequest_ = null;
        onChanged();
      } else {
        createTransactionRequest_ = null;
        createTransactionRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public common.request.TransactionRequestProto.Builder getCreateTransactionRequestBuilder() {
      
      onChanged();
      return getCreateTransactionRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    public common.request.TransactionRequestProtoOrBuilder getCreateTransactionRequestOrBuilder() {
      if (createTransactionRequestBuilder_ != null) {
        return createTransactionRequestBuilder_.getMessageOrBuilder();
      } else {
        return createTransactionRequest_ == null ?
            common.request.TransactionRequestProto.getDefaultInstance() : createTransactionRequest_;
      }
    }
    /**
     * <code>.transaction.TransactionRequestProto create_transaction_request = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        common.request.TransactionRequestProto, common.request.TransactionRequestProto.Builder, common.request.TransactionRequestProtoOrBuilder> 
        getCreateTransactionRequestFieldBuilder() {
      if (createTransactionRequestBuilder_ == null) {
        createTransactionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            common.request.TransactionRequestProto, common.request.TransactionRequestProto.Builder, common.request.TransactionRequestProtoOrBuilder>(
                getCreateTransactionRequest(),
                getParentForChildren(),
                isClean());
        createTransactionRequest_ = null;
      }
      return createTransactionRequestBuilder_;
    }

    private java.util.List<common.models.transaction.TransactionProto> transactionResponse_ =
      java.util.Collections.emptyList();
    private void ensureTransactionResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transactionResponse_ = new java.util.ArrayList<common.models.transaction.TransactionProto>(transactionResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        common.models.transaction.TransactionProto, common.models.transaction.TransactionProto.Builder, common.models.transaction.TransactionProtoOrBuilder> transactionResponseBuilder_;

    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public java.util.List<common.models.transaction.TransactionProto> getTransactionResponseList() {
      if (transactionResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactionResponse_);
      } else {
        return transactionResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public int getTransactionResponseCount() {
      if (transactionResponseBuilder_ == null) {
        return transactionResponse_.size();
      } else {
        return transactionResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public common.models.transaction.TransactionProto getTransactionResponse(int index) {
      if (transactionResponseBuilder_ == null) {
        return transactionResponse_.get(index);
      } else {
        return transactionResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder setTransactionResponse(
        int index, common.models.transaction.TransactionProto value) {
      if (transactionResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionResponseIsMutable();
        transactionResponse_.set(index, value);
        onChanged();
      } else {
        transactionResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder setTransactionResponse(
        int index, common.models.transaction.TransactionProto.Builder builderForValue) {
      if (transactionResponseBuilder_ == null) {
        ensureTransactionResponseIsMutable();
        transactionResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder addTransactionResponse(common.models.transaction.TransactionProto value) {
      if (transactionResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionResponseIsMutable();
        transactionResponse_.add(value);
        onChanged();
      } else {
        transactionResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder addTransactionResponse(
        int index, common.models.transaction.TransactionProto value) {
      if (transactionResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionResponseIsMutable();
        transactionResponse_.add(index, value);
        onChanged();
      } else {
        transactionResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder addTransactionResponse(
        common.models.transaction.TransactionProto.Builder builderForValue) {
      if (transactionResponseBuilder_ == null) {
        ensureTransactionResponseIsMutable();
        transactionResponse_.add(builderForValue.build());
        onChanged();
      } else {
        transactionResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder addTransactionResponse(
        int index, common.models.transaction.TransactionProto.Builder builderForValue) {
      if (transactionResponseBuilder_ == null) {
        ensureTransactionResponseIsMutable();
        transactionResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder addAllTransactionResponse(
        java.lang.Iterable<? extends common.models.transaction.TransactionProto> values) {
      if (transactionResponseBuilder_ == null) {
        ensureTransactionResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionResponse_);
        onChanged();
      } else {
        transactionResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder clearTransactionResponse() {
      if (transactionResponseBuilder_ == null) {
        transactionResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public Builder removeTransactionResponse(int index) {
      if (transactionResponseBuilder_ == null) {
        ensureTransactionResponseIsMutable();
        transactionResponse_.remove(index);
        onChanged();
      } else {
        transactionResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public common.models.transaction.TransactionProto.Builder getTransactionResponseBuilder(
        int index) {
      return getTransactionResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public common.models.transaction.TransactionProtoOrBuilder getTransactionResponseOrBuilder(
        int index) {
      if (transactionResponseBuilder_ == null) {
        return transactionResponse_.get(index);  } else {
        return transactionResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public java.util.List<? extends common.models.transaction.TransactionProtoOrBuilder> 
         getTransactionResponseOrBuilderList() {
      if (transactionResponseBuilder_ != null) {
        return transactionResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactionResponse_);
      }
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public common.models.transaction.TransactionProto.Builder addTransactionResponseBuilder() {
      return getTransactionResponseFieldBuilder().addBuilder(
          common.models.transaction.TransactionProto.getDefaultInstance());
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public common.models.transaction.TransactionProto.Builder addTransactionResponseBuilder(
        int index) {
      return getTransactionResponseFieldBuilder().addBuilder(
          index, common.models.transaction.TransactionProto.getDefaultInstance());
    }
    /**
     * <code>repeated .transaction.TransactionProto transaction_response = 30;</code>
     */
    public java.util.List<common.models.transaction.TransactionProto.Builder> 
         getTransactionResponseBuilderList() {
      return getTransactionResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        common.models.transaction.TransactionProto, common.models.transaction.TransactionProto.Builder, common.models.transaction.TransactionProtoOrBuilder> 
        getTransactionResponseFieldBuilder() {
      if (transactionResponseBuilder_ == null) {
        transactionResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            common.models.transaction.TransactionProto, common.models.transaction.TransactionProto.Builder, common.models.transaction.TransactionProtoOrBuilder>(
                transactionResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transactionResponse_ = null;
      }
      return transactionResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transaction.TransactionResponseProto)
  }

  // @@protoc_insertion_point(class_scope:transaction.TransactionResponseProto)
  private static final common.request.TransactionResponseProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new common.request.TransactionResponseProto();
  }

  public static common.request.TransactionResponseProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionResponseProto>
      PARSER = new com.google.protobuf.AbstractParser<TransactionResponseProto>() {
    @java.lang.Override
    public TransactionResponseProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionResponseProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionResponseProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionResponseProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public common.request.TransactionResponseProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

