export enum dashboardMenuList {
    PORTFOLIO = "PORTFOLIO",
    TRANSACTION = "TRANSACTION",
    POSITION = "POSITION",
    SECURITY = "SECURITY"
}

export enum booleanKeys{
  IS_SIDE_NAV_ACTIVE = "IS_SIDE_NAV_ACTIVE",
  IS_OBR_PROMPT_SHOWING = "IS_OBR_PROMPT_SHOWING",
  IS_SIGN_IN_OR_SIGN_UP = "IS_SIGN_IN_OR_SIGN_UP",
  IS_PASSWORD_VISIBLE = "IS_PASSWORD_VISIBLE",
  IS_FEATURE_ACTIVE = "IS_FEATURE_ACTIVE",
}