// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/position/query_position_request.proto

package fintekkers.requests.position;

public final class QueryPositionRequestProtos {
  private QueryPositionRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_requests_position_QueryPositionRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_requests_position_QueryPositionRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9fintekkers/requests/position/query_pos" +
      "ition_request.proto\022\034fintekkers.requests" +
      ".position\032&fintekkers/models/position/fi" +
      "eld.proto\032(fintekkers/models/position/me" +
      "asure.proto\032)fintekkers/models/position/" +
      "position.proto\0320fintekkers/models/positi" +
      "on/position_filter.proto\032,fintekkers/mod" +
      "els/util/local_timestamp.proto\032(fintekke" +
      "rs/requests/util/operation.proto\"\223\004\n\031Que" +
      "ryPositionRequestProto\022\024\n\014object_class\030\001" +
      " \001(\t\022\017\n\007version\030\002 \001(\t\022K\n\016operation_type\030" +
      "\n \001(\01623.fintekkers.requests.util.Request" +
      "OperationTypeProto\022D\n\rposition_type\030\024 \001(" +
      "\0162-.fintekkers.models.position.PositionT" +
      "ypeProto\022D\n\rposition_view\030\025 \001(\0162-.fintek" +
      "kers.models.position.PositionViewProto\0226" +
      "\n\006fields\030\036 \003(\0162&.fintekkers.models.posit" +
      "ion.FieldProto\022:\n\010measures\030\037 \003(\0162(.finte" +
      "kkers.models.position.MeasureProto\022F\n\rfi" +
      "lter_fields\030  \001(\0132/.fintekkers.models.po" +
      "sition.PositionFilterProto\022:\n\005as_of\030! \001(" +
      "\0132+.fintekkers.models.util.LocalTimestam" +
      "pProtoB\036B\032QueryPositionRequestProtosP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fintekkers.models.position.FieldProtos.getDescriptor(),
          fintekkers.models.position.MeasureProtos.getDescriptor(),
          fintekkers.models.position.PositionProtos.getDescriptor(),
          fintekkers.models.position.PositionFilterProtos.getDescriptor(),
          fintekkers.models.util.LocalTimestamp.getDescriptor(),
          fintekkers.requests.util.Operation.getDescriptor(),
        });
    internal_static_fintekkers_requests_position_QueryPositionRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fintekkers_requests_position_QueryPositionRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_requests_position_QueryPositionRequestProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "OperationType", "PositionType", "PositionView", "Fields", "Measures", "FilterFields", "AsOf", });
    fintekkers.models.position.FieldProtos.getDescriptor();
    fintekkers.models.position.MeasureProtos.getDescriptor();
    fintekkers.models.position.PositionProtos.getDescriptor();
    fintekkers.models.position.PositionFilterProtos.getDescriptor();
    fintekkers.models.util.LocalTimestamp.getDescriptor();
    fintekkers.requests.util.Operation.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
