import * as jspb from 'google-protobuf'



export enum FieldProto { 
  UNKNOWN_FIELD = 0,
  ID = 1,
  EFFECTIVE_DATE = 10,
  STRATEGY = 11,
  SECURITY = 12,
  SECURITY_DESCRIPTION = 61,
  CASH_IMPACT_SECURITY = 13,
  ASSET_CLASS = 50,
  PRODUCT_CLASS = 51,
  PRODUCT_TYPE = 52,
  SECURITY_ID = 53,
  IDENTIFIER = 54,
  TENOR = 55,
  MATURITY_DATE = 56,
  ADJUSTED_TENOR = 57,
  PORTFOLIO = 14,
  PORTFOLIO_ID = 15,
  PORTFOLIO_NAME = 60,
  PRICE = 16,
  PRICE_ID = 17,
  IS_CANCELLED = 18,
  POSITION_STATUS = 19,
  TRADE_DATE = 30,
  SETTLEMENT_DATE = 31,
  TRANSACTION_TYPE = 32,
  TAX_LOT_OPEN_DATE = 40,
  TAX_LOT_CLOSE_DATE = 41,
}
