# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/position/query_position_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.position import field_pb2 as models_dot_position_dot_field__pb2
from models.position import measure_pb2 as models_dot_position_dot_measure__pb2
from models.position import position_pb2 as models_dot_position_dot_position__pb2
from models.position import position_filter_pb2 as models_dot_position_dot_position__filter__pb2
from models.util import local_timestamp_pb2 as models_dot_util_dot_local__timestamp__pb2
from requests.util import operation_pb2 as requests_dot_util_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.requests/position/query_position_request.proto\x12\x08position\x1a\x1bmodels/position/field.proto\x1a\x1dmodels/position/measure.proto\x1a\x1emodels/position/position.proto\x1a%models/position/position_filter.proto\x1a!models/util/local_timestamp.proto\x1a\x1drequests/util/operation.proto\"\x93\x03\n\x19QueryPositionRequestProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x37\n\x0eoperation_type\x18\n \x01(\x0e\x32\x1f.util.RequestOperationTypeProto\x12\x32\n\rposition_type\x18\x14 \x01(\x0e\x32\x1b.position.PositionTypeProto\x12\x32\n\rposition_view\x18\x15 \x01(\x0e\x32\x1b.position.PositionViewProto\x12$\n\x06\x66ields\x18\x1e \x03(\x0e\x32\x14.position.FieldProto\x12(\n\x08measures\x18\x1f \x03(\x0e\x32\x16.position.MeasureProto\x12\x34\n\rfilter_fields\x18  \x01(\x0b\x32\x1d.position.PositionFilterProto\x12(\n\x05\x61s_of\x18! \x01(\x0b\x32\x19.util.LocalTimestampProtoB.\n\x0e\x63ommon.requestB\x1aQueryPositionRequestProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.position.query_position_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016common.requestB\032QueryPositionRequestProtosP\001'
  _QUERYPOSITIONREQUESTPROTO._serialized_start=258
  _QUERYPOSITIONREQUESTPROTO._serialized_end=661
# @@protoc_insertion_point(module_scope)
