// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/position/position_response.proto

package common.request.protos;

public interface PositionResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:position.PositionResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>.position.PositionRequestProto position_request = 11;</code>
   * @return Whether the positionRequest field is set.
   */
  boolean hasPositionRequest();
  /**
   * <code>.position.PositionRequestProto position_request = 11;</code>
   * @return The positionRequest.
   */
  common.request.protos.PositionRequestProto getPositionRequest();
  /**
   * <code>.position.PositionRequestProto position_request = 11;</code>
   */
  common.request.protos.PositionRequestProtoOrBuilder getPositionRequestOrBuilder();

  /**
   * <pre>
   *TODO - Think about how to model this long term; ISO code vs. UUID vs. full security object
   * </pre>
   *
   * <code>string reporting_currency = 12;</code>
   * @return The reportingCurrency.
   */
  java.lang.String getReportingCurrency();
  /**
   * <pre>
   *TODO - Think about how to model this long term; ISO code vs. UUID vs. full security object
   * </pre>
   *
   * <code>string reporting_currency = 12;</code>
   * @return The bytes for reportingCurrency.
   */
  com.google.protobuf.ByteString
      getReportingCurrencyBytes();

  /**
   * <code>repeated .position.PositionProto positions = 30;</code>
   */
  java.util.List<common.model.protos.PositionProto> 
      getPositionsList();
  /**
   * <code>repeated .position.PositionProto positions = 30;</code>
   */
  common.model.protos.PositionProto getPositions(int index);
  /**
   * <code>repeated .position.PositionProto positions = 30;</code>
   */
  int getPositionsCount();
  /**
   * <code>repeated .position.PositionProto positions = 30;</code>
   */
  java.util.List<? extends common.model.protos.PositionProtoOrBuilder> 
      getPositionsOrBuilderList();
  /**
   * <code>repeated .position.PositionProto positions = 30;</code>
   */
  common.model.protos.PositionProtoOrBuilder getPositionsOrBuilder(
      int index);
}
