// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/util/lock/lock_response.proto

package fintekkers.requests.util.lock;

/**
 * Protobuf type {@code fintekkers.requests.util.lock.LockResponseProto}
 */
public final class LockResponseProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.requests.util.lock.LockResponseProto)
    LockResponseProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LockResponseProto.newBuilder() to construct.
  private LockResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LockResponseProto() {
    objectClass_ = "";
    version_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LockResponseProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LockResponseProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            objectClass_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 26: {
            fintekkers.requests.util.lock.LockRequestProto.Builder subBuilder = null;
            if (getLockRequest_ != null) {
              subBuilder = getLockRequest_.toBuilder();
            }
            getLockRequest_ = input.readMessage(fintekkers.requests.util.lock.LockRequestProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(getLockRequest_);
              getLockRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder subBuilder = null;
            if (lockResponse_ != null) {
              subBuilder = lockResponse_.toBuilder();
            }
            lockResponse_ = input.readMessage(fintekkers.models.util.lock.NodeStateOuterClass.NodeState.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lockResponse_);
              lockResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 322: {
            fintekkers.requests.util.errors.Summary.SummaryProto.Builder subBuilder = null;
            if (errorsOrWarnings_ != null) {
              subBuilder = errorsOrWarnings_.toBuilder();
            }
            errorsOrWarnings_ = input.readMessage(fintekkers.requests.util.errors.Summary.SummaryProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(errorsOrWarnings_);
              errorsOrWarnings_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.requests.util.lock.LockResponseProtos.internal_static_fintekkers_requests_util_lock_LockResponseProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.requests.util.lock.LockResponseProtos.internal_static_fintekkers_requests_util_lock_LockResponseProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.requests.util.lock.LockResponseProto.class, fintekkers.requests.util.lock.LockResponseProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectClass_;
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GET_LOCK_REQUEST_FIELD_NUMBER = 3;
  private fintekkers.requests.util.lock.LockRequestProto getLockRequest_;
  /**
   * <pre>
   *The request that this response is for
   * </pre>
   *
   * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
   * @return Whether the getLockRequest field is set.
   */
  @java.lang.Override
  public boolean hasGetLockRequest() {
    return getLockRequest_ != null;
  }
  /**
   * <pre>
   *The request that this response is for
   * </pre>
   *
   * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
   * @return The getLockRequest.
   */
  @java.lang.Override
  public fintekkers.requests.util.lock.LockRequestProto getGetLockRequest() {
    return getLockRequest_ == null ? fintekkers.requests.util.lock.LockRequestProto.getDefaultInstance() : getLockRequest_;
  }
  /**
   * <pre>
   *The request that this response is for
   * </pre>
   *
   * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
   */
  @java.lang.Override
  public fintekkers.requests.util.lock.LockRequestProtoOrBuilder getGetLockRequestOrBuilder() {
    return getGetLockRequest();
  }

  public static final int LOCK_RESPONSE_FIELD_NUMBER = 4;
  private fintekkers.models.util.lock.NodeStateOuterClass.NodeState lockResponse_;
  /**
   * <pre>
   *Returns the node, and its state that was granted to the caller. If this is empty
   *then there will be details in the {errors_or_warning} variable
   * </pre>
   *
   * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
   * @return Whether the lockResponse field is set.
   */
  @java.lang.Override
  public boolean hasLockResponse() {
    return lockResponse_ != null;
  }
  /**
   * <pre>
   *Returns the node, and its state that was granted to the caller. If this is empty
   *then there will be details in the {errors_or_warning} variable
   * </pre>
   *
   * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
   * @return The lockResponse.
   */
  @java.lang.Override
  public fintekkers.models.util.lock.NodeStateOuterClass.NodeState getLockResponse() {
    return lockResponse_ == null ? fintekkers.models.util.lock.NodeStateOuterClass.NodeState.getDefaultInstance() : lockResponse_;
  }
  /**
   * <pre>
   *Returns the node, and its state that was granted to the caller. If this is empty
   *then there will be details in the {errors_or_warning} variable
   * </pre>
   *
   * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.lock.NodeStateOuterClass.NodeStateOrBuilder getLockResponseOrBuilder() {
    return getLockResponse();
  }

  public static final int ERRORS_OR_WARNINGS_FIELD_NUMBER = 40;
  private fintekkers.requests.util.errors.Summary.SummaryProto errorsOrWarnings_;
  /**
   * <pre>
   *If no errors or warnings in the response then the request was processed successfully without any
   *contingencies.
   * </pre>
   *
   * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   * @return Whether the errorsOrWarnings field is set.
   */
  @java.lang.Override
  public boolean hasErrorsOrWarnings() {
    return errorsOrWarnings_ != null;
  }
  /**
   * <pre>
   *If no errors or warnings in the response then the request was processed successfully without any
   *contingencies.
   * </pre>
   *
   * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   * @return The errorsOrWarnings.
   */
  @java.lang.Override
  public fintekkers.requests.util.errors.Summary.SummaryProto getErrorsOrWarnings() {
    return errorsOrWarnings_ == null ? fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance() : errorsOrWarnings_;
  }
  /**
   * <pre>
   *If no errors or warnings in the response then the request was processed successfully without any
   *contingencies.
   * </pre>
   *
   * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder getErrorsOrWarningsOrBuilder() {
    return getErrorsOrWarnings();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getObjectClassBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (getLockRequest_ != null) {
      output.writeMessage(3, getGetLockRequest());
    }
    if (lockResponse_ != null) {
      output.writeMessage(4, getLockResponse());
    }
    if (errorsOrWarnings_ != null) {
      output.writeMessage(40, getErrorsOrWarnings());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getObjectClassBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (getLockRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGetLockRequest());
    }
    if (lockResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLockResponse());
    }
    if (errorsOrWarnings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(40, getErrorsOrWarnings());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.requests.util.lock.LockResponseProto)) {
      return super.equals(obj);
    }
    fintekkers.requests.util.lock.LockResponseProto other = (fintekkers.requests.util.lock.LockResponseProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasGetLockRequest() != other.hasGetLockRequest()) return false;
    if (hasGetLockRequest()) {
      if (!getGetLockRequest()
          .equals(other.getGetLockRequest())) return false;
    }
    if (hasLockResponse() != other.hasLockResponse()) return false;
    if (hasLockResponse()) {
      if (!getLockResponse()
          .equals(other.getLockResponse())) return false;
    }
    if (hasErrorsOrWarnings() != other.hasErrorsOrWarnings()) return false;
    if (hasErrorsOrWarnings()) {
      if (!getErrorsOrWarnings()
          .equals(other.getErrorsOrWarnings())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasGetLockRequest()) {
      hash = (37 * hash) + GET_LOCK_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getGetLockRequest().hashCode();
    }
    if (hasLockResponse()) {
      hash = (37 * hash) + LOCK_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getLockResponse().hashCode();
    }
    if (hasErrorsOrWarnings()) {
      hash = (37 * hash) + ERRORS_OR_WARNINGS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorsOrWarnings().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.util.lock.LockResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.requests.util.lock.LockResponseProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintekkers.requests.util.lock.LockResponseProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.requests.util.lock.LockResponseProto)
      fintekkers.requests.util.lock.LockResponseProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.requests.util.lock.LockResponseProtos.internal_static_fintekkers_requests_util_lock_LockResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.requests.util.lock.LockResponseProtos.internal_static_fintekkers_requests_util_lock_LockResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.requests.util.lock.LockResponseProto.class, fintekkers.requests.util.lock.LockResponseProto.Builder.class);
    }

    // Construct using fintekkers.requests.util.lock.LockResponseProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectClass_ = "";

      version_ = "";

      if (getLockRequestBuilder_ == null) {
        getLockRequest_ = null;
      } else {
        getLockRequest_ = null;
        getLockRequestBuilder_ = null;
      }
      if (lockResponseBuilder_ == null) {
        lockResponse_ = null;
      } else {
        lockResponse_ = null;
        lockResponseBuilder_ = null;
      }
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarnings_ = null;
      } else {
        errorsOrWarnings_ = null;
        errorsOrWarningsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.requests.util.lock.LockResponseProtos.internal_static_fintekkers_requests_util_lock_LockResponseProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.requests.util.lock.LockResponseProto getDefaultInstanceForType() {
      return fintekkers.requests.util.lock.LockResponseProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.requests.util.lock.LockResponseProto build() {
      fintekkers.requests.util.lock.LockResponseProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.requests.util.lock.LockResponseProto buildPartial() {
      fintekkers.requests.util.lock.LockResponseProto result = new fintekkers.requests.util.lock.LockResponseProto(this);
      result.objectClass_ = objectClass_;
      result.version_ = version_;
      if (getLockRequestBuilder_ == null) {
        result.getLockRequest_ = getLockRequest_;
      } else {
        result.getLockRequest_ = getLockRequestBuilder_.build();
      }
      if (lockResponseBuilder_ == null) {
        result.lockResponse_ = lockResponse_;
      } else {
        result.lockResponse_ = lockResponseBuilder_.build();
      }
      if (errorsOrWarningsBuilder_ == null) {
        result.errorsOrWarnings_ = errorsOrWarnings_;
      } else {
        result.errorsOrWarnings_ = errorsOrWarningsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.requests.util.lock.LockResponseProto) {
        return mergeFrom((fintekkers.requests.util.lock.LockResponseProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.requests.util.lock.LockResponseProto other) {
      if (other == fintekkers.requests.util.lock.LockResponseProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasGetLockRequest()) {
        mergeGetLockRequest(other.getGetLockRequest());
      }
      if (other.hasLockResponse()) {
        mergeLockResponse(other.getLockResponse());
      }
      if (other.hasErrorsOrWarnings()) {
        mergeErrorsOrWarnings(other.getErrorsOrWarnings());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      fintekkers.requests.util.lock.LockResponseProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (fintekkers.requests.util.lock.LockResponseProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      
      objectClass_ = getDefaultInstance().getObjectClass();
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private fintekkers.requests.util.lock.LockRequestProto getLockRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.util.lock.LockRequestProto, fintekkers.requests.util.lock.LockRequestProto.Builder, fintekkers.requests.util.lock.LockRequestProtoOrBuilder> getLockRequestBuilder_;
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     * @return Whether the getLockRequest field is set.
     */
    public boolean hasGetLockRequest() {
      return getLockRequestBuilder_ != null || getLockRequest_ != null;
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     * @return The getLockRequest.
     */
    public fintekkers.requests.util.lock.LockRequestProto getGetLockRequest() {
      if (getLockRequestBuilder_ == null) {
        return getLockRequest_ == null ? fintekkers.requests.util.lock.LockRequestProto.getDefaultInstance() : getLockRequest_;
      } else {
        return getLockRequestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public Builder setGetLockRequest(fintekkers.requests.util.lock.LockRequestProto value) {
      if (getLockRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        getLockRequest_ = value;
        onChanged();
      } else {
        getLockRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public Builder setGetLockRequest(
        fintekkers.requests.util.lock.LockRequestProto.Builder builderForValue) {
      if (getLockRequestBuilder_ == null) {
        getLockRequest_ = builderForValue.build();
        onChanged();
      } else {
        getLockRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public Builder mergeGetLockRequest(fintekkers.requests.util.lock.LockRequestProto value) {
      if (getLockRequestBuilder_ == null) {
        if (getLockRequest_ != null) {
          getLockRequest_ =
            fintekkers.requests.util.lock.LockRequestProto.newBuilder(getLockRequest_).mergeFrom(value).buildPartial();
        } else {
          getLockRequest_ = value;
        }
        onChanged();
      } else {
        getLockRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public Builder clearGetLockRequest() {
      if (getLockRequestBuilder_ == null) {
        getLockRequest_ = null;
        onChanged();
      } else {
        getLockRequest_ = null;
        getLockRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public fintekkers.requests.util.lock.LockRequestProto.Builder getGetLockRequestBuilder() {
      
      onChanged();
      return getGetLockRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    public fintekkers.requests.util.lock.LockRequestProtoOrBuilder getGetLockRequestOrBuilder() {
      if (getLockRequestBuilder_ != null) {
        return getLockRequestBuilder_.getMessageOrBuilder();
      } else {
        return getLockRequest_ == null ?
            fintekkers.requests.util.lock.LockRequestProto.getDefaultInstance() : getLockRequest_;
      }
    }
    /**
     * <pre>
     *The request that this response is for
     * </pre>
     *
     * <code>.fintekkers.requests.util.lock.LockRequestProto get_lock_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.util.lock.LockRequestProto, fintekkers.requests.util.lock.LockRequestProto.Builder, fintekkers.requests.util.lock.LockRequestProtoOrBuilder> 
        getGetLockRequestFieldBuilder() {
      if (getLockRequestBuilder_ == null) {
        getLockRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.util.lock.LockRequestProto, fintekkers.requests.util.lock.LockRequestProto.Builder, fintekkers.requests.util.lock.LockRequestProtoOrBuilder>(
                getGetLockRequest(),
                getParentForChildren(),
                isClean());
        getLockRequest_ = null;
      }
      return getLockRequestBuilder_;
    }

    private fintekkers.models.util.lock.NodeStateOuterClass.NodeState lockResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.lock.NodeStateOuterClass.NodeState, fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder, fintekkers.models.util.lock.NodeStateOuterClass.NodeStateOrBuilder> lockResponseBuilder_;
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     * @return Whether the lockResponse field is set.
     */
    public boolean hasLockResponse() {
      return lockResponseBuilder_ != null || lockResponse_ != null;
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     * @return The lockResponse.
     */
    public fintekkers.models.util.lock.NodeStateOuterClass.NodeState getLockResponse() {
      if (lockResponseBuilder_ == null) {
        return lockResponse_ == null ? fintekkers.models.util.lock.NodeStateOuterClass.NodeState.getDefaultInstance() : lockResponse_;
      } else {
        return lockResponseBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public Builder setLockResponse(fintekkers.models.util.lock.NodeStateOuterClass.NodeState value) {
      if (lockResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lockResponse_ = value;
        onChanged();
      } else {
        lockResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public Builder setLockResponse(
        fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder builderForValue) {
      if (lockResponseBuilder_ == null) {
        lockResponse_ = builderForValue.build();
        onChanged();
      } else {
        lockResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public Builder mergeLockResponse(fintekkers.models.util.lock.NodeStateOuterClass.NodeState value) {
      if (lockResponseBuilder_ == null) {
        if (lockResponse_ != null) {
          lockResponse_ =
            fintekkers.models.util.lock.NodeStateOuterClass.NodeState.newBuilder(lockResponse_).mergeFrom(value).buildPartial();
        } else {
          lockResponse_ = value;
        }
        onChanged();
      } else {
        lockResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public Builder clearLockResponse() {
      if (lockResponseBuilder_ == null) {
        lockResponse_ = null;
        onChanged();
      } else {
        lockResponse_ = null;
        lockResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder getLockResponseBuilder() {
      
      onChanged();
      return getLockResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    public fintekkers.models.util.lock.NodeStateOuterClass.NodeStateOrBuilder getLockResponseOrBuilder() {
      if (lockResponseBuilder_ != null) {
        return lockResponseBuilder_.getMessageOrBuilder();
      } else {
        return lockResponse_ == null ?
            fintekkers.models.util.lock.NodeStateOuterClass.NodeState.getDefaultInstance() : lockResponse_;
      }
    }
    /**
     * <pre>
     *Returns the node, and its state that was granted to the caller. If this is empty
     *then there will be details in the {errors_or_warning} variable
     * </pre>
     *
     * <code>.fintekkers.models.util.lock.NodeState lock_response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.lock.NodeStateOuterClass.NodeState, fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder, fintekkers.models.util.lock.NodeStateOuterClass.NodeStateOrBuilder> 
        getLockResponseFieldBuilder() {
      if (lockResponseBuilder_ == null) {
        lockResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.lock.NodeStateOuterClass.NodeState, fintekkers.models.util.lock.NodeStateOuterClass.NodeState.Builder, fintekkers.models.util.lock.NodeStateOuterClass.NodeStateOrBuilder>(
                getLockResponse(),
                getParentForChildren(),
                isClean());
        lockResponse_ = null;
      }
      return lockResponseBuilder_;
    }

    private fintekkers.requests.util.errors.Summary.SummaryProto errorsOrWarnings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> errorsOrWarningsBuilder_;
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     * @return Whether the errorsOrWarnings field is set.
     */
    public boolean hasErrorsOrWarnings() {
      return errorsOrWarningsBuilder_ != null || errorsOrWarnings_ != null;
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     * @return The errorsOrWarnings.
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto getErrorsOrWarnings() {
      if (errorsOrWarningsBuilder_ == null) {
        return errorsOrWarnings_ == null ? fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance() : errorsOrWarnings_;
      } else {
        return errorsOrWarningsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder setErrorsOrWarnings(fintekkers.requests.util.errors.Summary.SummaryProto value) {
      if (errorsOrWarningsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        errorsOrWarnings_ = value;
        onChanged();
      } else {
        errorsOrWarningsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder setErrorsOrWarnings(
        fintekkers.requests.util.errors.Summary.SummaryProto.Builder builderForValue) {
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarnings_ = builderForValue.build();
        onChanged();
      } else {
        errorsOrWarningsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder mergeErrorsOrWarnings(fintekkers.requests.util.errors.Summary.SummaryProto value) {
      if (errorsOrWarningsBuilder_ == null) {
        if (errorsOrWarnings_ != null) {
          errorsOrWarnings_ =
            fintekkers.requests.util.errors.Summary.SummaryProto.newBuilder(errorsOrWarnings_).mergeFrom(value).buildPartial();
        } else {
          errorsOrWarnings_ = value;
        }
        onChanged();
      } else {
        errorsOrWarningsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder clearErrorsOrWarnings() {
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarnings_ = null;
        onChanged();
      } else {
        errorsOrWarnings_ = null;
        errorsOrWarningsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto.Builder getErrorsOrWarningsBuilder() {
      
      onChanged();
      return getErrorsOrWarningsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder getErrorsOrWarningsOrBuilder() {
      if (errorsOrWarningsBuilder_ != null) {
        return errorsOrWarningsBuilder_.getMessageOrBuilder();
      } else {
        return errorsOrWarnings_ == null ?
            fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance() : errorsOrWarnings_;
      }
    }
    /**
     * <pre>
     *If no errors or warnings in the response then the request was processed successfully without any
     *contingencies.
     * </pre>
     *
     * <code>.fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> 
        getErrorsOrWarningsFieldBuilder() {
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarningsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder>(
                getErrorsOrWarnings(),
                getParentForChildren(),
                isClean());
        errorsOrWarnings_ = null;
      }
      return errorsOrWarningsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.requests.util.lock.LockResponseProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.requests.util.lock.LockResponseProto)
  private static final fintekkers.requests.util.lock.LockResponseProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.requests.util.lock.LockResponseProto();
  }

  public static fintekkers.requests.util.lock.LockResponseProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LockResponseProto>
      PARSER = new com.google.protobuf.AbstractParser<LockResponseProto>() {
    @java.lang.Override
    public LockResponseProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LockResponseProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LockResponseProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LockResponseProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.requests.util.lock.LockResponseProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

