// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/valuation_response.proto

package fintekkers.requests.valuation;

public interface ValuationResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintekkers.requests.valuation.ValuationResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>.fintekkers.requests.valuation.ValuationRequestProto valuation_request = 20;</code>
   * @return Whether the valuationRequest field is set.
   */
  boolean hasValuationRequest();
  /**
   * <code>.fintekkers.requests.valuation.ValuationRequestProto valuation_request = 20;</code>
   * @return The valuationRequest.
   */
  fintekkers.requests.valuation.ValuationRequestProto getValuationRequest();
  /**
   * <code>.fintekkers.requests.valuation.ValuationRequestProto valuation_request = 20;</code>
   */
  fintekkers.requests.valuation.ValuationRequestProtoOrBuilder getValuationRequestOrBuilder();

  /**
   * <code>repeated .fintekkers.models.position.MeasureMapEntry measure_results = 30;</code>
   */
  java.util.List<fintekkers.models.position.MeasureMapEntry> 
      getMeasureResultsList();
  /**
   * <code>repeated .fintekkers.models.position.MeasureMapEntry measure_results = 30;</code>
   */
  fintekkers.models.position.MeasureMapEntry getMeasureResults(int index);
  /**
   * <code>repeated .fintekkers.models.position.MeasureMapEntry measure_results = 30;</code>
   */
  int getMeasureResultsCount();
  /**
   * <code>repeated .fintekkers.models.position.MeasureMapEntry measure_results = 30;</code>
   */
  java.util.List<? extends fintekkers.models.position.MeasureMapEntryOrBuilder> 
      getMeasureResultsOrBuilderList();
  /**
   * <code>repeated .fintekkers.models.position.MeasureMapEntry measure_results = 30;</code>
   */
  fintekkers.models.position.MeasureMapEntryOrBuilder getMeasureResultsOrBuilder(
      int index);
}
