# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/portfolio-service/portfolio_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from requests.portfolio import create_portfolio_request_pb2 as requests_dot_portfolio_dot_create__portfolio__request__pb2
from requests.portfolio import create_portfolio_response_pb2 as requests_dot_portfolio_dot_create__portfolio__response__pb2
from requests.portfolio import query_portfolio_request_pb2 as requests_dot_portfolio_dot_query__portfolio__request__pb2
from requests.portfolio import query_portfolio_response_pb2 as requests_dot_portfolio_dot_query__portfolio__response__pb2
from requests.util.errors import summary_pb2 as requests_dot_util_dot_errors_dot_summary__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2services/portfolio-service/portfolio_service.proto\x12\x10security_service\x1a\x31requests/portfolio/create_portfolio_request.proto\x1a\x32requests/portfolio/create_portfolio_response.proto\x1a\x30requests/portfolio/query_portfolio_request.proto\x1a\x31requests/portfolio/query_portfolio_response.proto\x1a\"requests/util/errors/summary.proto2\xb3\x04\n\tPortfolio\x12\x61\n\x0e\x43reateOrUpdate\x12&.portfolio.CreatePortfolioRequestProto\x1a\'.portfolio.CreatePortfolioResponseProto\x12Y\n\x08GetByIDs\x12%.portfolio.QueryPortfolioRequestProto\x1a&.portfolio.QueryPortfolioResponseProto\x12W\n\x06Search\x12%.portfolio.QueryPortfolioRequestProto\x1a&.portfolio.QueryPortfolioResponseProto\x12X\n\x07ListIDs\x12%.portfolio.QueryPortfolioRequestProto\x1a&.portfolio.QueryPortfolioResponseProto\x12[\n\x16ValidateCreateOrUpdate\x12&.portfolio.CreatePortfolioRequestProto\x1a\x19.util.errors.SummaryProto\x12X\n\x14ValidateQueryRequest\x12%.portfolio.QueryPortfolioRequestProto\x1a\x19.util.errors.SummaryProtoB\x13\n\x0e\x63ommon.service\x88\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.portfolio_service.portfolio_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016common.service\210\001\001'
  _PORTFOLIO._serialized_start=313
  _PORTFOLIO._serialized_end=876
# @@protoc_insertion_point(module_scope)
