// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/requests/position/position_request.proto

package common.request.protos;

public final class PositionRequestProtos {
  private PositionRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_position_PositionRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_position_PositionRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/protos/requests/position/position_requ" +
      "est.proto\022\010position\032\"protos/models/posit" +
      "ion/field.proto\032$protos/models/position/" +
      "measure.proto\032%protos/models/position/po" +
      "sition.proto\032,protos/models/position/pos" +
      "ition_filter.proto\032(protos/models/util/l" +
      "ocal_timestamp.proto\032$protos/requests/ut" +
      "il/operation.proto\"\216\003\n\024PositionRequestPr" +
      "oto\022\024\n\014object_class\030\001 \001(\t\022\017\n\007version\030\002 \001" +
      "(\t\0227\n\016operation_type\030\n \001(\0162\037.util.Reques" +
      "tOperationTypeProto\0222\n\rposition_type\030\024 \001" +
      "(\0162\033.position.PositionTypeProto\0222\n\rposit" +
      "ion_view\030\025 \001(\0162\033.position.PositionViewPr" +
      "oto\022$\n\006fields\030\036 \003(\0162\024.position.FieldProt" +
      "o\022(\n\010measures\030\037 \003(\0162\026.position.MeasurePr" +
      "oto\0224\n\rfilter_fields\030  \001(\0132\035.position.Po" +
      "sitionFilterProto\022(\n\005as_of\030! \001(\0132\031.util." +
      "LocalTimestampProtoB0\n\025common.request.pr" +
      "otosB\025PositionRequestProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.model.protos.FieldProtos.getDescriptor(),
          common.model.protos.MeasureProtos.getDescriptor(),
          common.model.protos.PositionProtos.getDescriptor(),
          common.model.protos.PositionFilterProtos.getDescriptor(),
          common.model.protoUtils.LocalTimestamp.getDescriptor(),
          util.Operation.getDescriptor(),
        });
    internal_static_position_PositionRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_position_PositionRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_position_PositionRequestProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "OperationType", "PositionType", "PositionView", "Fields", "Measures", "FilterFields", "AsOf", });
    common.model.protos.FieldProtos.getDescriptor();
    common.model.protos.MeasureProtos.getDescriptor();
    common.model.protos.PositionProtos.getDescriptor();
    common.model.protos.PositionFilterProtos.getDescriptor();
    common.model.protoUtils.LocalTimestamp.getDescriptor();
    util.Operation.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
