// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/requests/transaction/transaction_response.proto

package common.request.protos;

public final class TransactionResponseProtos {
  private TransactionResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transaction_TransactionResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transaction_TransactionResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6protos/requests/transaction/transactio" +
      "n_response.proto\022\013transaction\032+protos/mo" +
      "dels/transaction/transaction.proto\0325prot" +
      "os/requests/transaction/transaction_requ" +
      "est.proto\"\310\001\n\030TransactionResponseProto\022\024" +
      "\n\014object_class\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022H\n" +
      "\032create_transaction_request\030\024 \001(\0132$.tran" +
      "saction.TransactionRequestProto\022;\n\024trans" +
      "action_response\030\036 \003(\0132\035.transaction.Tran" +
      "sactionProtoB4\n\025common.request.protosB\031T" +
      "ransactionResponseProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.model.protos.TransactionProtos.getDescriptor(),
          common.request.protos.TransactionRequestProtos.getDescriptor(),
        });
    internal_static_transaction_TransactionResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transaction_TransactionResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transaction_TransactionResponseProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "CreateTransactionRequest", "TransactionResponse", });
    common.model.protos.TransactionProtos.getDescriptor();
    common.request.protos.TransactionRequestProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
