// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/requests/portfolio/portfolio_response.proto

package common.request.protos;

public final class PortfolioResponseProtos {
  private PortfolioResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_portfolio_PortfolioResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_portfolio_PortfolioResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2protos/requests/portfolio/portfolio_re" +
      "sponse.proto\022\tportfolio\032\'protos/models/p" +
      "ortfolio/portfolio.proto\0321protos/request" +
      "s/portfolio/portfolio_request.proto\"\272\001\n\026" +
      "PortfolioResponseProto\022\024\n\014object_class\030\001" +
      " \001(\t\022\017\n\007version\030\002 \001(\t\022B\n\030create_portfoli" +
      "o_request\030\024 \001(\0132 .portfolio.PortfolioReq" +
      "uestProto\0225\n\022portfolio_response\030\036 \003(\0132\031." +
      "portfolio.PortfolioProtoB2\n\025common.reque" +
      "st.protosB\027PortfolioResponseProtosP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.model.protos.PortfolioProtos.getDescriptor(),
          common.request.protos.PortfolioRequestProtos.getDescriptor(),
        });
    internal_static_portfolio_PortfolioResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_portfolio_PortfolioResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_portfolio_PortfolioResponseProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "CreatePortfolioRequest", "PortfolioResponse", });
    common.model.protos.PortfolioProtos.getDescriptor();
    common.request.protos.PortfolioRequestProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
