// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/position/position_status.proto

package common.model.protos;

/**
 * Protobuf enum {@code position.PositionStatusProto}
 */
public enum PositionStatusProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <pre>
   *This trade may never happen
   * </pre>
   *
   * <code>HYPOTHETICAL = 1;</code>
   */
  HYPOTHETICAL(1),
  /**
   * <pre>
   *This trade is expected to happen, but hasn't been executed yet
   * </pre>
   *
   * <code>INTENDED = 2;</code>
   */
  INTENDED(2),
  /**
   * <pre>
   *Beneficial ownership changes related to this transaction are now legally binding
   * </pre>
   *
   * <code>EXECUTED = 3;</code>
   */
  EXECUTED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <pre>
   *This trade may never happen
   * </pre>
   *
   * <code>HYPOTHETICAL = 1;</code>
   */
  public static final int HYPOTHETICAL_VALUE = 1;
  /**
   * <pre>
   *This trade is expected to happen, but hasn't been executed yet
   * </pre>
   *
   * <code>INTENDED = 2;</code>
   */
  public static final int INTENDED_VALUE = 2;
  /**
   * <pre>
   *Beneficial ownership changes related to this transaction are now legally binding
   * </pre>
   *
   * <code>EXECUTED = 3;</code>
   */
  public static final int EXECUTED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PositionStatusProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PositionStatusProto forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return HYPOTHETICAL;
      case 2: return INTENDED;
      case 3: return EXECUTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PositionStatusProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PositionStatusProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PositionStatusProto>() {
          public PositionStatusProto findValueByNumber(int number) {
            return PositionStatusProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return common.model.protos.PositionStatusProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final PositionStatusProto[] VALUES = values();

  public static PositionStatusProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PositionStatusProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:position.PositionStatusProto)
}

