// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/transaction/transaction.proto

package common.model.protos;

public interface TransactionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.TransactionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   *Primary Key
   * </pre>
   *
   * <code>.util.UUIDProto uuid = 5;</code>
   * @return Whether the uuid field is set.
   */
  boolean hasUuid();
  /**
   * <pre>
   *Primary Key
   * </pre>
   *
   * <code>.util.UUIDProto uuid = 5;</code>
   * @return The uuid.
   */
  common.model.protoUtils.Uuid.UUIDProto getUuid();
  /**
   * <pre>
   *Primary Key
   * </pre>
   *
   * <code>.util.UUIDProto uuid = 5;</code>
   */
  common.model.protoUtils.Uuid.UUIDProtoOrBuilder getUuidOrBuilder();

  /**
   * <code>.util.LocalTimestampProto as_of = 6;</code>
   * @return Whether the asOf field is set.
   */
  boolean hasAsOf();
  /**
   * <code>.util.LocalTimestampProto as_of = 6;</code>
   * @return The asOf.
   */
  common.model.protoUtils.LocalTimestamp.LocalTimestampProto getAsOf();
  /**
   * <code>.util.LocalTimestampProto as_of = 6;</code>
   */
  common.model.protoUtils.LocalTimestamp.LocalTimestampProtoOrBuilder getAsOfOrBuilder();

  /**
   * <code>bool is_link = 7;</code>
   * @return The isLink.
   */
  boolean getIsLink();

  /**
   * <pre>
   *Transaction details
   * </pre>
   *
   * <code>.portfolio.PortfolioProto portfolio = 10;</code>
   * @return Whether the portfolio field is set.
   */
  boolean hasPortfolio();
  /**
   * <pre>
   *Transaction details
   * </pre>
   *
   * <code>.portfolio.PortfolioProto portfolio = 10;</code>
   * @return The portfolio.
   */
  common.model.protos.PortfolioProto getPortfolio();
  /**
   * <pre>
   *Transaction details
   * </pre>
   *
   * <code>.portfolio.PortfolioProto portfolio = 10;</code>
   */
  common.model.protos.PortfolioProtoOrBuilder getPortfolioOrBuilder();

  /**
   * <code>.security.SecurityProto security = 11;</code>
   * @return Whether the security field is set.
   */
  boolean hasSecurity();
  /**
   * <code>.security.SecurityProto security = 11;</code>
   * @return The security.
   */
  common.model.protos.SecurityProto getSecurity();
  /**
   * <code>.security.SecurityProto security = 11;</code>
   */
  common.model.protos.SecurityProtoOrBuilder getSecurityOrBuilder();

  /**
   * <code>.transaction.TransactionTypeProto transaction_type = 12;</code>
   * @return The enum numeric value on the wire for transactionType.
   */
  int getTransactionTypeValue();
  /**
   * <code>.transaction.TransactionTypeProto transaction_type = 12;</code>
   * @return The transactionType.
   */
  common.model.protos.TransactionTypeProto getTransactionType();

  /**
   * <code>.util.DecimalValueProto quantity = 13;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>.util.DecimalValueProto quantity = 13;</code>
   * @return The quantity.
   */
  common.model.protoUtils.DecimalValue.DecimalValueProto getQuantity();
  /**
   * <code>.util.DecimalValueProto quantity = 13;</code>
   */
  common.model.protoUtils.DecimalValue.DecimalValueProtoOrBuilder getQuantityOrBuilder();

  /**
   * <code>.price.PriceProto price = 14;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>.price.PriceProto price = 14;</code>
   * @return The price.
   */
  common.model.protos.PriceProto getPrice();
  /**
   * <code>.price.PriceProto price = 14;</code>
   */
  common.model.protos.PriceProtoOrBuilder getPriceOrBuilder();

  /**
   * <pre>
   *NOTE: We're using timestamps for dates. The time portion will be ignored when parsing
   * </pre>
   *
   * <code>.util.LocalDateProto trade_date = 15;</code>
   * @return Whether the tradeDate field is set.
   */
  boolean hasTradeDate();
  /**
   * <pre>
   *NOTE: We're using timestamps for dates. The time portion will be ignored when parsing
   * </pre>
   *
   * <code>.util.LocalDateProto trade_date = 15;</code>
   * @return The tradeDate.
   */
  common.model.protoUtils.LocalDate.LocalDateProto getTradeDate();
  /**
   * <pre>
   *NOTE: We're using timestamps for dates. The time portion will be ignored when parsing
   * </pre>
   *
   * <code>.util.LocalDateProto trade_date = 15;</code>
   */
  common.model.protoUtils.LocalDate.LocalDateProtoOrBuilder getTradeDateOrBuilder();

  /**
   * <code>.util.LocalDateProto settlement_date = 16;</code>
   * @return Whether the settlementDate field is set.
   */
  boolean hasSettlementDate();
  /**
   * <code>.util.LocalDateProto settlement_date = 16;</code>
   * @return The settlementDate.
   */
  common.model.protoUtils.LocalDate.LocalDateProto getSettlementDate();
  /**
   * <code>.util.LocalDateProto settlement_date = 16;</code>
   */
  common.model.protoUtils.LocalDate.LocalDateProtoOrBuilder getSettlementDateOrBuilder();

  /**
   * <pre>
   *Lineage
   *  TransactionProto cashTransaction = 20;
   *  TransactionProto parentTransaction = 21;
   * </pre>
   *
   * <code>repeated .transaction.TransactionProto childTransactions = 20;</code>
   */
  java.util.List<common.model.protos.TransactionProto> 
      getChildTransactionsList();
  /**
   * <pre>
   *Lineage
   *  TransactionProto cashTransaction = 20;
   *  TransactionProto parentTransaction = 21;
   * </pre>
   *
   * <code>repeated .transaction.TransactionProto childTransactions = 20;</code>
   */
  common.model.protos.TransactionProto getChildTransactions(int index);
  /**
   * <pre>
   *Lineage
   *  TransactionProto cashTransaction = 20;
   *  TransactionProto parentTransaction = 21;
   * </pre>
   *
   * <code>repeated .transaction.TransactionProto childTransactions = 20;</code>
   */
  int getChildTransactionsCount();
  /**
   * <pre>
   *Lineage
   *  TransactionProto cashTransaction = 20;
   *  TransactionProto parentTransaction = 21;
   * </pre>
   *
   * <code>repeated .transaction.TransactionProto childTransactions = 20;</code>
   */
  java.util.List<? extends common.model.protos.TransactionProtoOrBuilder> 
      getChildTransactionsOrBuilderList();
  /**
   * <pre>
   *Lineage
   *  TransactionProto cashTransaction = 20;
   *  TransactionProto parentTransaction = 21;
   * </pre>
   *
   * <code>repeated .transaction.TransactionProto childTransactions = 20;</code>
   */
  common.model.protos.TransactionProtoOrBuilder getChildTransactionsOrBuilder(
      int index);

  /**
   * <pre>
   *Business metadata
   * </pre>
   *
   * <code>.position.PositionStatusProto position_status = 25;</code>
   * @return The enum numeric value on the wire for positionStatus.
   */
  int getPositionStatusValue();
  /**
   * <pre>
   *Business metadata
   * </pre>
   *
   * <code>.position.PositionStatusProto position_status = 25;</code>
   * @return The positionStatus.
   */
  common.model.protos.PositionStatusProto getPositionStatus();

  /**
   * <code>string trade_name = 26;</code>
   * @return The tradeName.
   */
  java.lang.String getTradeName();
  /**
   * <code>string trade_name = 26;</code>
   * @return The bytes for tradeName.
   */
  com.google.protobuf.ByteString
      getTradeNameBytes();

  /**
   * <code>.strategy.StrategyAllocationProto strategy_allocation = 27;</code>
   * @return Whether the strategyAllocation field is set.
   */
  boolean hasStrategyAllocation();
  /**
   * <code>.strategy.StrategyAllocationProto strategy_allocation = 27;</code>
   * @return The strategyAllocation.
   */
  common.model.protos.StrategyAllocationProto getStrategyAllocation();
  /**
   * <code>.strategy.StrategyAllocationProto strategy_allocation = 27;</code>
   */
  common.model.protos.StrategyAllocationProtoOrBuilder getStrategyAllocationOrBuilder();

  /**
   * <pre>
   *System-based fields
   * </pre>
   *
   * <code>bool is_cancelled = 30;</code>
   * @return The isCancelled.
   */
  boolean getIsCancelled();
}
