# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/valuation/valuation_response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.position import position_util_pb2 as models_dot_position_dot_position__util__pb2
from requests.valuation import valuation_request_pb2 as requests_dot_valuation_dot_valuation__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+requests/valuation/valuation_response.proto\x12\tvaluation\x1a#models/position/position_util.proto\x1a*requests/valuation/valuation_request.proto\"\xb0\x01\n\x16ValuationResponseProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12;\n\x11valuation_request\x18\x14 \x01(\x0b\x32 .valuation.ValuationRequestProto\x12\x32\n\x0fmeasure_results\x18\x1e \x03(\x0b\x32\x19.position.MeasureMapEntryB+\n\x0e\x63ommon.requestB\x17ValuationResponseProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.valuation.valuation_response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016common.requestB\027ValuationResponseProtosP\001'
  _VALUATIONRESPONSEPROTO._serialized_start=140
  _VALUATIONRESPONSEPROTO._serialized_end=316
# @@protoc_insertion_point(module_scope)
