// source: fintekkers/requests/portfolio/create_portfolio_response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var fintekkers_models_portfolio_portfolio_pb = require('../../../fintekkers/models/portfolio/portfolio_pb.js');
goog.object.extend(proto, fintekkers_models_portfolio_portfolio_pb);
var fintekkers_requests_portfolio_create_portfolio_request_pb = require('../../../fintekkers/requests/portfolio/create_portfolio_request_pb.js');
goog.object.extend(proto, fintekkers_requests_portfolio_create_portfolio_request_pb);
goog.exportSymbol('proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.repeatedFields_, null);
};
goog.inherits(proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.displayName = 'proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.repeatedFields_ = [30];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.toObject = function(opt_includeInstance) {
  return proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectClass: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, ""),
    createPortfolioRequest: (f = msg.getCreatePortfolioRequest()) && fintekkers_requests_portfolio_create_portfolio_request_pb.CreatePortfolioRequestProto.toObject(includeInstance, f),
    portfolioResponseList: jspb.Message.toObjectList(msg.getPortfolioResponseList(),
    fintekkers_models_portfolio_portfolio_pb.PortfolioProto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto;
  return proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectClass(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 20:
      var value = new fintekkers_requests_portfolio_create_portfolio_request_pb.CreatePortfolioRequestProto;
      reader.readMessage(value,fintekkers_requests_portfolio_create_portfolio_request_pb.CreatePortfolioRequestProto.deserializeBinaryFromReader);
      msg.setCreatePortfolioRequest(value);
      break;
    case 30:
      var value = new fintekkers_models_portfolio_portfolio_pb.PortfolioProto;
      reader.readMessage(value,fintekkers_models_portfolio_portfolio_pb.PortfolioProto.deserializeBinaryFromReader);
      msg.addPortfolioResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectClass();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCreatePortfolioRequest();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      fintekkers_requests_portfolio_create_portfolio_request_pb.CreatePortfolioRequestProto.serializeBinaryToWriter
    );
  }
  f = message.getPortfolioResponseList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      30,
      f,
      fintekkers_models_portfolio_portfolio_pb.PortfolioProto.serializeBinaryToWriter
    );
  }
};


/**
 * optional string object_class = 1;
 * @return {string}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.getObjectClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.setObjectClass = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CreatePortfolioRequestProto create_portfolio_request = 20;
 * @return {?proto.fintekkers.requests.portfolio.CreatePortfolioRequestProto}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.getCreatePortfolioRequest = function() {
  return /** @type{?proto.fintekkers.requests.portfolio.CreatePortfolioRequestProto} */ (
    jspb.Message.getWrapperField(this, fintekkers_requests_portfolio_create_portfolio_request_pb.CreatePortfolioRequestProto, 20));
};


/**
 * @param {?proto.fintekkers.requests.portfolio.CreatePortfolioRequestProto|undefined} value
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
*/
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.setCreatePortfolioRequest = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.clearCreatePortfolioRequest = function() {
  return this.setCreatePortfolioRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.hasCreatePortfolioRequest = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * repeated fintekkers.models.portfolio.PortfolioProto portfolio_response = 30;
 * @return {!Array<!proto.fintekkers.models.portfolio.PortfolioProto>}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.getPortfolioResponseList = function() {
  return /** @type{!Array<!proto.fintekkers.models.portfolio.PortfolioProto>} */ (
    jspb.Message.getRepeatedWrapperField(this, fintekkers_models_portfolio_portfolio_pb.PortfolioProto, 30));
};


/**
 * @param {!Array<!proto.fintekkers.models.portfolio.PortfolioProto>} value
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
*/
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.setPortfolioResponseList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 30, value);
};


/**
 * @param {!proto.fintekkers.models.portfolio.PortfolioProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fintekkers.models.portfolio.PortfolioProto}
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.addPortfolioResponse = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 30, opt_value, proto.fintekkers.models.portfolio.PortfolioProto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto} returns this
 */
proto.fintekkers.requests.portfolio.CreatePortfolioResponseProto.prototype.clearPortfolioResponseList = function() {
  return this.setPortfolioResponseList([]);
};


goog.object.extend(exports, proto.fintekkers.requests.portfolio);
