# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/security/identifier/identifier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.security.identifier import identifier_type_pb2 as models_dot_security_dot_identifier_dot_identifier__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+models/security/identifier/identifier.proto\x12\x08security\x1a\x30models/security/identifier/identifier_type.proto\"\x8a\x01\n\x0fIdentifierProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x18\n\x10identifier_value\x18\x05 \x01(\t\x12\x36\n\x0fidentifier_type\x18\x06 \x01(\x0e\x32\x1d.security.IdentifierTypeProtoB7\n!common.models.security.identifierB\x10IdentifierProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.security.identifier.identifier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!common.models.security.identifierB\020IdentifierProtosP\001'
  _IDENTIFIERPROTO._serialized_start=108
  _IDENTIFIERPROTO._serialized_end=246
# @@protoc_insertion_point(module_scope)
