// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/position/position_util.proto

package fintekkers.models.position;

/**
 * Protobuf type {@code fintekkers.models.position.MeasureMapEntry}
 */
public final class MeasureMapEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.models.position.MeasureMapEntry)
    MeasureMapEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MeasureMapEntry.newBuilder() to construct.
  private MeasureMapEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MeasureMapEntry() {
    field_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MeasureMapEntry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MeasureMapEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            field_ = rawValue;
            break;
          }
          case 18: {
            fintekkers.models.util.DecimalValue.DecimalValueProto.Builder subBuilder = null;
            if (measureValue_ != null) {
              subBuilder = measureValue_.toBuilder();
            }
            measureValue_ = input.readMessage(fintekkers.models.util.DecimalValue.DecimalValueProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(measureValue_);
              measureValue_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.models.position.PositionUtilProtos.internal_static_fintekkers_models_position_MeasureMapEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.models.position.PositionUtilProtos.internal_static_fintekkers_models_position_MeasureMapEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.models.position.MeasureMapEntry.class, fintekkers.models.position.MeasureMapEntry.Builder.class);
  }

  public static final int FIELD_FIELD_NUMBER = 1;
  private int field_;
  /**
   * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
   * @return The enum numeric value on the wire for field.
   */
  @java.lang.Override public int getFieldValue() {
    return field_;
  }
  /**
   * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
   * @return The field.
   */
  @java.lang.Override public fintekkers.models.position.MeasureProto getField() {
    @SuppressWarnings("deprecation")
    fintekkers.models.position.MeasureProto result = fintekkers.models.position.MeasureProto.valueOf(field_);
    return result == null ? fintekkers.models.position.MeasureProto.UNRECOGNIZED : result;
  }

  public static final int MEASURE_VALUE_FIELD_NUMBER = 2;
  private fintekkers.models.util.DecimalValue.DecimalValueProto measureValue_;
  /**
   * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
   * @return Whether the measureValue field is set.
   */
  @java.lang.Override
  public boolean hasMeasureValue() {
    return measureValue_ != null;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
   * @return The measureValue.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getMeasureValue() {
    return measureValue_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : measureValue_;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getMeasureValueOrBuilder() {
    return getMeasureValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (field_ != fintekkers.models.position.MeasureProto.UNKNOWN_MEASURE.getNumber()) {
      output.writeEnum(1, field_);
    }
    if (measureValue_ != null) {
      output.writeMessage(2, getMeasureValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (field_ != fintekkers.models.position.MeasureProto.UNKNOWN_MEASURE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, field_);
    }
    if (measureValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMeasureValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.models.position.MeasureMapEntry)) {
      return super.equals(obj);
    }
    fintekkers.models.position.MeasureMapEntry other = (fintekkers.models.position.MeasureMapEntry) obj;

    if (field_ != other.field_) return false;
    if (hasMeasureValue() != other.hasMeasureValue()) return false;
    if (hasMeasureValue()) {
      if (!getMeasureValue()
          .equals(other.getMeasureValue())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIELD_FIELD_NUMBER;
    hash = (53 * hash) + field_;
    if (hasMeasureValue()) {
      hash = (37 * hash) + MEASURE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getMeasureValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.position.MeasureMapEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.models.position.MeasureMapEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.position.MeasureMapEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.models.position.MeasureMapEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintekkers.models.position.MeasureMapEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.models.position.MeasureMapEntry)
      fintekkers.models.position.MeasureMapEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.models.position.PositionUtilProtos.internal_static_fintekkers_models_position_MeasureMapEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.models.position.PositionUtilProtos.internal_static_fintekkers_models_position_MeasureMapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.models.position.MeasureMapEntry.class, fintekkers.models.position.MeasureMapEntry.Builder.class);
    }

    // Construct using fintekkers.models.position.MeasureMapEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      field_ = 0;

      if (measureValueBuilder_ == null) {
        measureValue_ = null;
      } else {
        measureValue_ = null;
        measureValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.models.position.PositionUtilProtos.internal_static_fintekkers_models_position_MeasureMapEntry_descriptor;
    }

    @java.lang.Override
    public fintekkers.models.position.MeasureMapEntry getDefaultInstanceForType() {
      return fintekkers.models.position.MeasureMapEntry.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.models.position.MeasureMapEntry build() {
      fintekkers.models.position.MeasureMapEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.models.position.MeasureMapEntry buildPartial() {
      fintekkers.models.position.MeasureMapEntry result = new fintekkers.models.position.MeasureMapEntry(this);
      result.field_ = field_;
      if (measureValueBuilder_ == null) {
        result.measureValue_ = measureValue_;
      } else {
        result.measureValue_ = measureValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.models.position.MeasureMapEntry) {
        return mergeFrom((fintekkers.models.position.MeasureMapEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.models.position.MeasureMapEntry other) {
      if (other == fintekkers.models.position.MeasureMapEntry.getDefaultInstance()) return this;
      if (other.field_ != 0) {
        setFieldValue(other.getFieldValue());
      }
      if (other.hasMeasureValue()) {
        mergeMeasureValue(other.getMeasureValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      fintekkers.models.position.MeasureMapEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (fintekkers.models.position.MeasureMapEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int field_ = 0;
    /**
     * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
     * @return The enum numeric value on the wire for field.
     */
    @java.lang.Override public int getFieldValue() {
      return field_;
    }
    /**
     * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
     * @param value The enum numeric value on the wire for field to set.
     * @return This builder for chaining.
     */
    public Builder setFieldValue(int value) {
      
      field_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public fintekkers.models.position.MeasureProto getField() {
      @SuppressWarnings("deprecation")
      fintekkers.models.position.MeasureProto result = fintekkers.models.position.MeasureProto.valueOf(field_);
      return result == null ? fintekkers.models.position.MeasureProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
     * @param value The field to set.
     * @return This builder for chaining.
     */
    public Builder setField(fintekkers.models.position.MeasureProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      field_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.models.position.MeasureProto field = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearField() {
      
      field_ = 0;
      onChanged();
      return this;
    }

    private fintekkers.models.util.DecimalValue.DecimalValueProto measureValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> measureValueBuilder_;
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     * @return Whether the measureValue field is set.
     */
    public boolean hasMeasureValue() {
      return measureValueBuilder_ != null || measureValue_ != null;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     * @return The measureValue.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getMeasureValue() {
      if (measureValueBuilder_ == null) {
        return measureValue_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : measureValue_;
      } else {
        return measureValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public Builder setMeasureValue(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (measureValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        measureValue_ = value;
        onChanged();
      } else {
        measureValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public Builder setMeasureValue(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (measureValueBuilder_ == null) {
        measureValue_ = builderForValue.build();
        onChanged();
      } else {
        measureValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public Builder mergeMeasureValue(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (measureValueBuilder_ == null) {
        if (measureValue_ != null) {
          measureValue_ =
            fintekkers.models.util.DecimalValue.DecimalValueProto.newBuilder(measureValue_).mergeFrom(value).buildPartial();
        } else {
          measureValue_ = value;
        }
        onChanged();
      } else {
        measureValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public Builder clearMeasureValue() {
      if (measureValueBuilder_ == null) {
        measureValue_ = null;
        onChanged();
      } else {
        measureValue_ = null;
        measureValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getMeasureValueBuilder() {
      
      onChanged();
      return getMeasureValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getMeasureValueOrBuilder() {
      if (measureValueBuilder_ != null) {
        return measureValueBuilder_.getMessageOrBuilder();
      } else {
        return measureValue_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : measureValue_;
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto measure_value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getMeasureValueFieldBuilder() {
      if (measureValueBuilder_ == null) {
        measureValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getMeasureValue(),
                getParentForChildren(),
                isClean());
        measureValue_ = null;
      }
      return measureValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.models.position.MeasureMapEntry)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.models.position.MeasureMapEntry)
  private static final fintekkers.models.position.MeasureMapEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.models.position.MeasureMapEntry();
  }

  public static fintekkers.models.position.MeasureMapEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MeasureMapEntry>
      PARSER = new com.google.protobuf.AbstractParser<MeasureMapEntry>() {
    @java.lang.Override
    public MeasureMapEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MeasureMapEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MeasureMapEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MeasureMapEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.models.position.MeasureMapEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

