// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/security/query_security_response.proto

package fintekkers.requests.security;

/**
 * Protobuf type {@code fintekkers.requests.security.QuerySecurityResponseProto}
 */
public final class QuerySecurityResponseProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.requests.security.QuerySecurityResponseProto)
    QuerySecurityResponseProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuerySecurityResponseProto.newBuilder() to construct.
  private QuerySecurityResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuerySecurityResponseProto() {
    objectClass_ = "";
    version_ = "";
    securityResponse_ = java.util.Collections.emptyList();
    errorsOrWarnings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuerySecurityResponseProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuerySecurityResponseProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            objectClass_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 162: {
            fintekkers.requests.security.QuerySecurityRequestProto.Builder subBuilder = null;
            if (querySecurityInput_ != null) {
              subBuilder = querySecurityInput_.toBuilder();
            }
            querySecurityInput_ = input.readMessage(fintekkers.requests.security.QuerySecurityRequestProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(querySecurityInput_);
              querySecurityInput_ = subBuilder.buildPartial();
            }

            break;
          }
          case 242: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              securityResponse_ = new java.util.ArrayList<fintekkers.models.security.SecurityProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            securityResponse_.add(
                input.readMessage(fintekkers.models.security.SecurityProto.parser(), extensionRegistry));
            break;
          }
          case 322: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              errorsOrWarnings_ = new java.util.ArrayList<fintekkers.requests.util.errors.Summary.SummaryProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            errorsOrWarnings_.add(
                input.readMessage(fintekkers.requests.util.errors.Summary.SummaryProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        securityResponse_ = java.util.Collections.unmodifiableList(securityResponse_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        errorsOrWarnings_ = java.util.Collections.unmodifiableList(errorsOrWarnings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.requests.security.QuerySecurityResponseProtos.internal_static_fintekkers_requests_security_QuerySecurityResponseProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.requests.security.QuerySecurityResponseProtos.internal_static_fintekkers_requests_security_QuerySecurityResponseProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.requests.security.QuerySecurityResponseProto.class, fintekkers.requests.security.QuerySecurityResponseProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectClass_;
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_SECURITY_INPUT_FIELD_NUMBER = 20;
  private fintekkers.requests.security.QuerySecurityRequestProto querySecurityInput_;
  /**
   * <pre>
   *The input that was provided for this request.
   * </pre>
   *
   * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
   * @return Whether the querySecurityInput field is set.
   */
  @java.lang.Override
  public boolean hasQuerySecurityInput() {
    return querySecurityInput_ != null;
  }
  /**
   * <pre>
   *The input that was provided for this request.
   * </pre>
   *
   * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
   * @return The querySecurityInput.
   */
  @java.lang.Override
  public fintekkers.requests.security.QuerySecurityRequestProto getQuerySecurityInput() {
    return querySecurityInput_ == null ? fintekkers.requests.security.QuerySecurityRequestProto.getDefaultInstance() : querySecurityInput_;
  }
  /**
   * <pre>
   *The input that was provided for this request.
   * </pre>
   *
   * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
   */
  @java.lang.Override
  public fintekkers.requests.security.QuerySecurityRequestProtoOrBuilder getQuerySecurityInputOrBuilder() {
    return getQuerySecurityInput();
  }

  public static final int SECURITY_RESPONSE_FIELD_NUMBER = 30;
  private java.util.List<fintekkers.models.security.SecurityProto> securityResponse_;
  /**
   * <pre>
   *The security (or securities) that was matched by this request.
   * </pre>
   *
   * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<fintekkers.models.security.SecurityProto> getSecurityResponseList() {
    return securityResponse_;
  }
  /**
   * <pre>
   *The security (or securities) that was matched by this request.
   * </pre>
   *
   * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<? extends fintekkers.models.security.SecurityProtoOrBuilder> 
      getSecurityResponseOrBuilderList() {
    return securityResponse_;
  }
  /**
   * <pre>
   *The security (or securities) that was matched by this request.
   * </pre>
   *
   * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
   */
  @java.lang.Override
  public int getSecurityResponseCount() {
    return securityResponse_.size();
  }
  /**
   * <pre>
   *The security (or securities) that was matched by this request.
   * </pre>
   *
   * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
   */
  @java.lang.Override
  public fintekkers.models.security.SecurityProto getSecurityResponse(int index) {
    return securityResponse_.get(index);
  }
  /**
   * <pre>
   *The security (or securities) that was matched by this request.
   * </pre>
   *
   * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
   */
  @java.lang.Override
  public fintekkers.models.security.SecurityProtoOrBuilder getSecurityResponseOrBuilder(
      int index) {
    return securityResponse_.get(index);
  }

  public static final int ERRORS_OR_WARNINGS_FIELD_NUMBER = 40;
  private java.util.List<fintekkers.requests.util.errors.Summary.SummaryProto> errorsOrWarnings_;
  /**
   * <pre>
   *Any errors or warnings related to this request
   * </pre>
   *
   * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public java.util.List<fintekkers.requests.util.errors.Summary.SummaryProto> getErrorsOrWarningsList() {
    return errorsOrWarnings_;
  }
  /**
   * <pre>
   *Any errors or warnings related to this request
   * </pre>
   *
   * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public java.util.List<? extends fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> 
      getErrorsOrWarningsOrBuilderList() {
    return errorsOrWarnings_;
  }
  /**
   * <pre>
   *Any errors or warnings related to this request
   * </pre>
   *
   * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public int getErrorsOrWarningsCount() {
    return errorsOrWarnings_.size();
  }
  /**
   * <pre>
   *Any errors or warnings related to this request
   * </pre>
   *
   * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public fintekkers.requests.util.errors.Summary.SummaryProto getErrorsOrWarnings(int index) {
    return errorsOrWarnings_.get(index);
  }
  /**
   * <pre>
   *Any errors or warnings related to this request
   * </pre>
   *
   * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
   */
  @java.lang.Override
  public fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder getErrorsOrWarningsOrBuilder(
      int index) {
    return errorsOrWarnings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getObjectClassBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (querySecurityInput_ != null) {
      output.writeMessage(20, getQuerySecurityInput());
    }
    for (int i = 0; i < securityResponse_.size(); i++) {
      output.writeMessage(30, securityResponse_.get(i));
    }
    for (int i = 0; i < errorsOrWarnings_.size(); i++) {
      output.writeMessage(40, errorsOrWarnings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getObjectClassBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (querySecurityInput_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getQuerySecurityInput());
    }
    for (int i = 0; i < securityResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, securityResponse_.get(i));
    }
    for (int i = 0; i < errorsOrWarnings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(40, errorsOrWarnings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.requests.security.QuerySecurityResponseProto)) {
      return super.equals(obj);
    }
    fintekkers.requests.security.QuerySecurityResponseProto other = (fintekkers.requests.security.QuerySecurityResponseProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasQuerySecurityInput() != other.hasQuerySecurityInput()) return false;
    if (hasQuerySecurityInput()) {
      if (!getQuerySecurityInput()
          .equals(other.getQuerySecurityInput())) return false;
    }
    if (!getSecurityResponseList()
        .equals(other.getSecurityResponseList())) return false;
    if (!getErrorsOrWarningsList()
        .equals(other.getErrorsOrWarningsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasQuerySecurityInput()) {
      hash = (37 * hash) + QUERY_SECURITY_INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getQuerySecurityInput().hashCode();
    }
    if (getSecurityResponseCount() > 0) {
      hash = (37 * hash) + SECURITY_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityResponseList().hashCode();
    }
    if (getErrorsOrWarningsCount() > 0) {
      hash = (37 * hash) + ERRORS_OR_WARNINGS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorsOrWarningsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.security.QuerySecurityResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.requests.security.QuerySecurityResponseProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintekkers.requests.security.QuerySecurityResponseProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.requests.security.QuerySecurityResponseProto)
      fintekkers.requests.security.QuerySecurityResponseProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.requests.security.QuerySecurityResponseProtos.internal_static_fintekkers_requests_security_QuerySecurityResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.requests.security.QuerySecurityResponseProtos.internal_static_fintekkers_requests_security_QuerySecurityResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.requests.security.QuerySecurityResponseProto.class, fintekkers.requests.security.QuerySecurityResponseProto.Builder.class);
    }

    // Construct using fintekkers.requests.security.QuerySecurityResponseProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSecurityResponseFieldBuilder();
        getErrorsOrWarningsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectClass_ = "";

      version_ = "";

      if (querySecurityInputBuilder_ == null) {
        querySecurityInput_ = null;
      } else {
        querySecurityInput_ = null;
        querySecurityInputBuilder_ = null;
      }
      if (securityResponseBuilder_ == null) {
        securityResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        securityResponseBuilder_.clear();
      }
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarnings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        errorsOrWarningsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.requests.security.QuerySecurityResponseProtos.internal_static_fintekkers_requests_security_QuerySecurityResponseProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.requests.security.QuerySecurityResponseProto getDefaultInstanceForType() {
      return fintekkers.requests.security.QuerySecurityResponseProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.requests.security.QuerySecurityResponseProto build() {
      fintekkers.requests.security.QuerySecurityResponseProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.requests.security.QuerySecurityResponseProto buildPartial() {
      fintekkers.requests.security.QuerySecurityResponseProto result = new fintekkers.requests.security.QuerySecurityResponseProto(this);
      int from_bitField0_ = bitField0_;
      result.objectClass_ = objectClass_;
      result.version_ = version_;
      if (querySecurityInputBuilder_ == null) {
        result.querySecurityInput_ = querySecurityInput_;
      } else {
        result.querySecurityInput_ = querySecurityInputBuilder_.build();
      }
      if (securityResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          securityResponse_ = java.util.Collections.unmodifiableList(securityResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.securityResponse_ = securityResponse_;
      } else {
        result.securityResponse_ = securityResponseBuilder_.build();
      }
      if (errorsOrWarningsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          errorsOrWarnings_ = java.util.Collections.unmodifiableList(errorsOrWarnings_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.errorsOrWarnings_ = errorsOrWarnings_;
      } else {
        result.errorsOrWarnings_ = errorsOrWarningsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.requests.security.QuerySecurityResponseProto) {
        return mergeFrom((fintekkers.requests.security.QuerySecurityResponseProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.requests.security.QuerySecurityResponseProto other) {
      if (other == fintekkers.requests.security.QuerySecurityResponseProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasQuerySecurityInput()) {
        mergeQuerySecurityInput(other.getQuerySecurityInput());
      }
      if (securityResponseBuilder_ == null) {
        if (!other.securityResponse_.isEmpty()) {
          if (securityResponse_.isEmpty()) {
            securityResponse_ = other.securityResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSecurityResponseIsMutable();
            securityResponse_.addAll(other.securityResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.securityResponse_.isEmpty()) {
          if (securityResponseBuilder_.isEmpty()) {
            securityResponseBuilder_.dispose();
            securityResponseBuilder_ = null;
            securityResponse_ = other.securityResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            securityResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSecurityResponseFieldBuilder() : null;
          } else {
            securityResponseBuilder_.addAllMessages(other.securityResponse_);
          }
        }
      }
      if (errorsOrWarningsBuilder_ == null) {
        if (!other.errorsOrWarnings_.isEmpty()) {
          if (errorsOrWarnings_.isEmpty()) {
            errorsOrWarnings_ = other.errorsOrWarnings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureErrorsOrWarningsIsMutable();
            errorsOrWarnings_.addAll(other.errorsOrWarnings_);
          }
          onChanged();
        }
      } else {
        if (!other.errorsOrWarnings_.isEmpty()) {
          if (errorsOrWarningsBuilder_.isEmpty()) {
            errorsOrWarningsBuilder_.dispose();
            errorsOrWarningsBuilder_ = null;
            errorsOrWarnings_ = other.errorsOrWarnings_;
            bitField0_ = (bitField0_ & ~0x00000002);
            errorsOrWarningsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getErrorsOrWarningsFieldBuilder() : null;
          } else {
            errorsOrWarningsBuilder_.addAllMessages(other.errorsOrWarnings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      fintekkers.requests.security.QuerySecurityResponseProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (fintekkers.requests.security.QuerySecurityResponseProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      
      objectClass_ = getDefaultInstance().getObjectClass();
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private fintekkers.requests.security.QuerySecurityRequestProto querySecurityInput_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.security.QuerySecurityRequestProto, fintekkers.requests.security.QuerySecurityRequestProto.Builder, fintekkers.requests.security.QuerySecurityRequestProtoOrBuilder> querySecurityInputBuilder_;
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     * @return Whether the querySecurityInput field is set.
     */
    public boolean hasQuerySecurityInput() {
      return querySecurityInputBuilder_ != null || querySecurityInput_ != null;
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     * @return The querySecurityInput.
     */
    public fintekkers.requests.security.QuerySecurityRequestProto getQuerySecurityInput() {
      if (querySecurityInputBuilder_ == null) {
        return querySecurityInput_ == null ? fintekkers.requests.security.QuerySecurityRequestProto.getDefaultInstance() : querySecurityInput_;
      } else {
        return querySecurityInputBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public Builder setQuerySecurityInput(fintekkers.requests.security.QuerySecurityRequestProto value) {
      if (querySecurityInputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        querySecurityInput_ = value;
        onChanged();
      } else {
        querySecurityInputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public Builder setQuerySecurityInput(
        fintekkers.requests.security.QuerySecurityRequestProto.Builder builderForValue) {
      if (querySecurityInputBuilder_ == null) {
        querySecurityInput_ = builderForValue.build();
        onChanged();
      } else {
        querySecurityInputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public Builder mergeQuerySecurityInput(fintekkers.requests.security.QuerySecurityRequestProto value) {
      if (querySecurityInputBuilder_ == null) {
        if (querySecurityInput_ != null) {
          querySecurityInput_ =
            fintekkers.requests.security.QuerySecurityRequestProto.newBuilder(querySecurityInput_).mergeFrom(value).buildPartial();
        } else {
          querySecurityInput_ = value;
        }
        onChanged();
      } else {
        querySecurityInputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public Builder clearQuerySecurityInput() {
      if (querySecurityInputBuilder_ == null) {
        querySecurityInput_ = null;
        onChanged();
      } else {
        querySecurityInput_ = null;
        querySecurityInputBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public fintekkers.requests.security.QuerySecurityRequestProto.Builder getQuerySecurityInputBuilder() {
      
      onChanged();
      return getQuerySecurityInputFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    public fintekkers.requests.security.QuerySecurityRequestProtoOrBuilder getQuerySecurityInputOrBuilder() {
      if (querySecurityInputBuilder_ != null) {
        return querySecurityInputBuilder_.getMessageOrBuilder();
      } else {
        return querySecurityInput_ == null ?
            fintekkers.requests.security.QuerySecurityRequestProto.getDefaultInstance() : querySecurityInput_;
      }
    }
    /**
     * <pre>
     *The input that was provided for this request.
     * </pre>
     *
     * <code>.fintekkers.requests.security.QuerySecurityRequestProto query_security_input = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.security.QuerySecurityRequestProto, fintekkers.requests.security.QuerySecurityRequestProto.Builder, fintekkers.requests.security.QuerySecurityRequestProtoOrBuilder> 
        getQuerySecurityInputFieldBuilder() {
      if (querySecurityInputBuilder_ == null) {
        querySecurityInputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.security.QuerySecurityRequestProto, fintekkers.requests.security.QuerySecurityRequestProto.Builder, fintekkers.requests.security.QuerySecurityRequestProtoOrBuilder>(
                getQuerySecurityInput(),
                getParentForChildren(),
                isClean());
        querySecurityInput_ = null;
      }
      return querySecurityInputBuilder_;
    }

    private java.util.List<fintekkers.models.security.SecurityProto> securityResponse_ =
      java.util.Collections.emptyList();
    private void ensureSecurityResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        securityResponse_ = new java.util.ArrayList<fintekkers.models.security.SecurityProto>(securityResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder> securityResponseBuilder_;

    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public java.util.List<fintekkers.models.security.SecurityProto> getSecurityResponseList() {
      if (securityResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(securityResponse_);
      } else {
        return securityResponseBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public int getSecurityResponseCount() {
      if (securityResponseBuilder_ == null) {
        return securityResponse_.size();
      } else {
        return securityResponseBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public fintekkers.models.security.SecurityProto getSecurityResponse(int index) {
      if (securityResponseBuilder_ == null) {
        return securityResponse_.get(index);
      } else {
        return securityResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder setSecurityResponse(
        int index, fintekkers.models.security.SecurityProto value) {
      if (securityResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityResponseIsMutable();
        securityResponse_.set(index, value);
        onChanged();
      } else {
        securityResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder setSecurityResponse(
        int index, fintekkers.models.security.SecurityProto.Builder builderForValue) {
      if (securityResponseBuilder_ == null) {
        ensureSecurityResponseIsMutable();
        securityResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        securityResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder addSecurityResponse(fintekkers.models.security.SecurityProto value) {
      if (securityResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityResponseIsMutable();
        securityResponse_.add(value);
        onChanged();
      } else {
        securityResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder addSecurityResponse(
        int index, fintekkers.models.security.SecurityProto value) {
      if (securityResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityResponseIsMutable();
        securityResponse_.add(index, value);
        onChanged();
      } else {
        securityResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder addSecurityResponse(
        fintekkers.models.security.SecurityProto.Builder builderForValue) {
      if (securityResponseBuilder_ == null) {
        ensureSecurityResponseIsMutable();
        securityResponse_.add(builderForValue.build());
        onChanged();
      } else {
        securityResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder addSecurityResponse(
        int index, fintekkers.models.security.SecurityProto.Builder builderForValue) {
      if (securityResponseBuilder_ == null) {
        ensureSecurityResponseIsMutable();
        securityResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        securityResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder addAllSecurityResponse(
        java.lang.Iterable<? extends fintekkers.models.security.SecurityProto> values) {
      if (securityResponseBuilder_ == null) {
        ensureSecurityResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, securityResponse_);
        onChanged();
      } else {
        securityResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder clearSecurityResponse() {
      if (securityResponseBuilder_ == null) {
        securityResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        securityResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public Builder removeSecurityResponse(int index) {
      if (securityResponseBuilder_ == null) {
        ensureSecurityResponseIsMutable();
        securityResponse_.remove(index);
        onChanged();
      } else {
        securityResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public fintekkers.models.security.SecurityProto.Builder getSecurityResponseBuilder(
        int index) {
      return getSecurityResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public fintekkers.models.security.SecurityProtoOrBuilder getSecurityResponseOrBuilder(
        int index) {
      if (securityResponseBuilder_ == null) {
        return securityResponse_.get(index);  } else {
        return securityResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public java.util.List<? extends fintekkers.models.security.SecurityProtoOrBuilder> 
         getSecurityResponseOrBuilderList() {
      if (securityResponseBuilder_ != null) {
        return securityResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(securityResponse_);
      }
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public fintekkers.models.security.SecurityProto.Builder addSecurityResponseBuilder() {
      return getSecurityResponseFieldBuilder().addBuilder(
          fintekkers.models.security.SecurityProto.getDefaultInstance());
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public fintekkers.models.security.SecurityProto.Builder addSecurityResponseBuilder(
        int index) {
      return getSecurityResponseFieldBuilder().addBuilder(
          index, fintekkers.models.security.SecurityProto.getDefaultInstance());
    }
    /**
     * <pre>
     *The security (or securities) that was matched by this request.
     * </pre>
     *
     * <code>repeated .fintekkers.models.security.SecurityProto security_response = 30;</code>
     */
    public java.util.List<fintekkers.models.security.SecurityProto.Builder> 
         getSecurityResponseBuilderList() {
      return getSecurityResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder> 
        getSecurityResponseFieldBuilder() {
      if (securityResponseBuilder_ == null) {
        securityResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder>(
                securityResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        securityResponse_ = null;
      }
      return securityResponseBuilder_;
    }

    private java.util.List<fintekkers.requests.util.errors.Summary.SummaryProto> errorsOrWarnings_ =
      java.util.Collections.emptyList();
    private void ensureErrorsOrWarningsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        errorsOrWarnings_ = new java.util.ArrayList<fintekkers.requests.util.errors.Summary.SummaryProto>(errorsOrWarnings_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> errorsOrWarningsBuilder_;

    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public java.util.List<fintekkers.requests.util.errors.Summary.SummaryProto> getErrorsOrWarningsList() {
      if (errorsOrWarningsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(errorsOrWarnings_);
      } else {
        return errorsOrWarningsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public int getErrorsOrWarningsCount() {
      if (errorsOrWarningsBuilder_ == null) {
        return errorsOrWarnings_.size();
      } else {
        return errorsOrWarningsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto getErrorsOrWarnings(int index) {
      if (errorsOrWarningsBuilder_ == null) {
        return errorsOrWarnings_.get(index);
      } else {
        return errorsOrWarningsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder setErrorsOrWarnings(
        int index, fintekkers.requests.util.errors.Summary.SummaryProto value) {
      if (errorsOrWarningsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.set(index, value);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder setErrorsOrWarnings(
        int index, fintekkers.requests.util.errors.Summary.SummaryProto.Builder builderForValue) {
      if (errorsOrWarningsBuilder_ == null) {
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.set(index, builderForValue.build());
        onChanged();
      } else {
        errorsOrWarningsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder addErrorsOrWarnings(fintekkers.requests.util.errors.Summary.SummaryProto value) {
      if (errorsOrWarningsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.add(value);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder addErrorsOrWarnings(
        int index, fintekkers.requests.util.errors.Summary.SummaryProto value) {
      if (errorsOrWarningsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.add(index, value);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder addErrorsOrWarnings(
        fintekkers.requests.util.errors.Summary.SummaryProto.Builder builderForValue) {
      if (errorsOrWarningsBuilder_ == null) {
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.add(builderForValue.build());
        onChanged();
      } else {
        errorsOrWarningsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder addErrorsOrWarnings(
        int index, fintekkers.requests.util.errors.Summary.SummaryProto.Builder builderForValue) {
      if (errorsOrWarningsBuilder_ == null) {
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.add(index, builderForValue.build());
        onChanged();
      } else {
        errorsOrWarningsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder addAllErrorsOrWarnings(
        java.lang.Iterable<? extends fintekkers.requests.util.errors.Summary.SummaryProto> values) {
      if (errorsOrWarningsBuilder_ == null) {
        ensureErrorsOrWarningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorsOrWarnings_);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder clearErrorsOrWarnings() {
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarnings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public Builder removeErrorsOrWarnings(int index) {
      if (errorsOrWarningsBuilder_ == null) {
        ensureErrorsOrWarningsIsMutable();
        errorsOrWarnings_.remove(index);
        onChanged();
      } else {
        errorsOrWarningsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto.Builder getErrorsOrWarningsBuilder(
        int index) {
      return getErrorsOrWarningsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder getErrorsOrWarningsOrBuilder(
        int index) {
      if (errorsOrWarningsBuilder_ == null) {
        return errorsOrWarnings_.get(index);  } else {
        return errorsOrWarningsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public java.util.List<? extends fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> 
         getErrorsOrWarningsOrBuilderList() {
      if (errorsOrWarningsBuilder_ != null) {
        return errorsOrWarningsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(errorsOrWarnings_);
      }
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto.Builder addErrorsOrWarningsBuilder() {
      return getErrorsOrWarningsFieldBuilder().addBuilder(
          fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance());
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public fintekkers.requests.util.errors.Summary.SummaryProto.Builder addErrorsOrWarningsBuilder(
        int index) {
      return getErrorsOrWarningsFieldBuilder().addBuilder(
          index, fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance());
    }
    /**
     * <pre>
     *Any errors or warnings related to this request
     * </pre>
     *
     * <code>repeated .fintekkers.requests.util.errors.SummaryProto errors_or_warnings = 40;</code>
     */
    public java.util.List<fintekkers.requests.util.errors.Summary.SummaryProto.Builder> 
         getErrorsOrWarningsBuilderList() {
      return getErrorsOrWarningsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder> 
        getErrorsOrWarningsFieldBuilder() {
      if (errorsOrWarningsBuilder_ == null) {
        errorsOrWarningsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            fintekkers.requests.util.errors.Summary.SummaryProto, fintekkers.requests.util.errors.Summary.SummaryProto.Builder, fintekkers.requests.util.errors.Summary.SummaryProtoOrBuilder>(
                errorsOrWarnings_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        errorsOrWarnings_ = null;
      }
      return errorsOrWarningsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.requests.security.QuerySecurityResponseProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.requests.security.QuerySecurityResponseProto)
  private static final fintekkers.requests.security.QuerySecurityResponseProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.requests.security.QuerySecurityResponseProto();
  }

  public static fintekkers.requests.security.QuerySecurityResponseProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuerySecurityResponseProto>
      PARSER = new com.google.protobuf.AbstractParser<QuerySecurityResponseProto>() {
    @java.lang.Override
    public QuerySecurityResponseProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuerySecurityResponseProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuerySecurityResponseProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuerySecurityResponseProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.requests.security.QuerySecurityResponseProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

