// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/util/errors/error.proto

package util.errors;

public final class ErrorOuterClass {
  private ErrorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *Error codes are defined to allow clients to programmatically
   *respond to issues. The bar for creating a new error code should
   *be that the
   * </pre>
   *
   * Protobuf enum {@code util.errors.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_ERROR = 0;</code>
     */
    UNKNOWN_ERROR(0),
    /**
     * <pre>
     *TO THINK ABOUT
     * </pre>
     *
     * <code>WARNING = 1;</code>
     */
    WARNING(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_ERROR = 0;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 0;
    /**
     * <pre>
     *TO THINK ABOUT
     * </pre>
     *
     * <code>WARNING = 1;</code>
     */
    public static final int WARNING_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_ERROR;
        case 1: return WARNING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return util.errors.ErrorOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:util.errors.ErrorCode)
  }

  public interface ErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:util.errors.Error)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The code.
     */
    util.errors.ErrorOuterClass.ErrorCode getCode();

    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return Whether the detail field is set.
     */
    boolean hasDetail();
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return The detail.
     */
    util.errors.MessageOuterClass.Message getDetail();
    /**
     * <code>.util.errors.Message detail = 2;</code>
     */
    util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder();
  }
  /**
   * <pre>
   *An error is used for situations where a request cannot be processed successfully, either
   *from a technical perspective or a business perspective.
   * </pre>
   *
   * Protobuf type {@code util.errors.Error}
   */
  public static final class Error extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:util.errors.Error)
      ErrorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Error.newBuilder() to construct.
    private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Error() {
      code_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Error();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Error(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              util.errors.MessageOuterClass.Message.Builder subBuilder = null;
              if (detail_ != null) {
                subBuilder = detail_.toBuilder();
              }
              detail_ = input.readMessage(util.errors.MessageOuterClass.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(detail_);
                detail_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return util.errors.ErrorOuterClass.internal_static_util_errors_Error_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return util.errors.ErrorOuterClass.internal_static_util_errors_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              util.errors.ErrorOuterClass.Error.class, util.errors.ErrorOuterClass.Error.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The code.
     */
    @java.lang.Override public util.errors.ErrorOuterClass.ErrorCode getCode() {
      @SuppressWarnings("deprecation")
      util.errors.ErrorOuterClass.ErrorCode result = util.errors.ErrorOuterClass.ErrorCode.valueOf(code_);
      return result == null ? util.errors.ErrorOuterClass.ErrorCode.UNRECOGNIZED : result;
    }

    public static final int DETAIL_FIELD_NUMBER = 2;
    private util.errors.MessageOuterClass.Message detail_;
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return Whether the detail field is set.
     */
    @java.lang.Override
    public boolean hasDetail() {
      return detail_ != null;
    }
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return The detail.
     */
    @java.lang.Override
    public util.errors.MessageOuterClass.Message getDetail() {
      return detail_ == null ? util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
    }
    /**
     * <code>.util.errors.Message detail = 2;</code>
     */
    @java.lang.Override
    public util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder() {
      return getDetail();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != util.errors.ErrorOuterClass.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (detail_ != null) {
        output.writeMessage(2, getDetail());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != util.errors.ErrorOuterClass.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (detail_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDetail());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof util.errors.ErrorOuterClass.Error)) {
        return super.equals(obj);
      }
      util.errors.ErrorOuterClass.Error other = (util.errors.ErrorOuterClass.Error) obj;

      if (code_ != other.code_) return false;
      if (hasDetail() != other.hasDetail()) return false;
      if (hasDetail()) {
        if (!getDetail()
            .equals(other.getDetail())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      if (hasDetail()) {
        hash = (37 * hash) + DETAIL_FIELD_NUMBER;
        hash = (53 * hash) + getDetail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static util.errors.ErrorOuterClass.Error parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(util.errors.ErrorOuterClass.Error prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *An error is used for situations where a request cannot be processed successfully, either
     *from a technical perspective or a business perspective.
     * </pre>
     *
     * Protobuf type {@code util.errors.Error}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:util.errors.Error)
        util.errors.ErrorOuterClass.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Error_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                util.errors.ErrorOuterClass.Error.class, util.errors.ErrorOuterClass.Error.Builder.class);
      }

      // Construct using util.errors.ErrorOuterClass.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        if (detailBuilder_ == null) {
          detail_ = null;
        } else {
          detail_ = null;
          detailBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Error_descriptor;
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Error getDefaultInstanceForType() {
        return util.errors.ErrorOuterClass.Error.getDefaultInstance();
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Error build() {
        util.errors.ErrorOuterClass.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Error buildPartial() {
        util.errors.ErrorOuterClass.Error result = new util.errors.ErrorOuterClass.Error(this);
        result.code_ = code_;
        if (detailBuilder_ == null) {
          result.detail_ = detail_;
        } else {
          result.detail_ = detailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof util.errors.ErrorOuterClass.Error) {
          return mergeFrom((util.errors.ErrorOuterClass.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(util.errors.ErrorOuterClass.Error other) {
        if (other == util.errors.ErrorOuterClass.Error.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (other.hasDetail()) {
          mergeDetail(other.getDetail());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        util.errors.ErrorOuterClass.Error parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (util.errors.ErrorOuterClass.Error) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public util.errors.ErrorOuterClass.ErrorCode getCode() {
        @SuppressWarnings("deprecation")
        util.errors.ErrorOuterClass.ErrorCode result = util.errors.ErrorOuterClass.ErrorCode.valueOf(code_);
        return result == null ? util.errors.ErrorOuterClass.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(util.errors.ErrorOuterClass.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private util.errors.MessageOuterClass.Message detail_;
      private com.google.protobuf.SingleFieldBuilderV3<
          util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder> detailBuilder_;
      /**
       * <code>.util.errors.Message detail = 2;</code>
       * @return Whether the detail field is set.
       */
      public boolean hasDetail() {
        return detailBuilder_ != null || detail_ != null;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       * @return The detail.
       */
      public util.errors.MessageOuterClass.Message getDetail() {
        if (detailBuilder_ == null) {
          return detail_ == null ? util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
        } else {
          return detailBuilder_.getMessage();
        }
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder setDetail(util.errors.MessageOuterClass.Message value) {
        if (detailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detail_ = value;
          onChanged();
        } else {
          detailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder setDetail(
          util.errors.MessageOuterClass.Message.Builder builderForValue) {
        if (detailBuilder_ == null) {
          detail_ = builderForValue.build();
          onChanged();
        } else {
          detailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder mergeDetail(util.errors.MessageOuterClass.Message value) {
        if (detailBuilder_ == null) {
          if (detail_ != null) {
            detail_ =
              util.errors.MessageOuterClass.Message.newBuilder(detail_).mergeFrom(value).buildPartial();
          } else {
            detail_ = value;
          }
          onChanged();
        } else {
          detailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder clearDetail() {
        if (detailBuilder_ == null) {
          detail_ = null;
          onChanged();
        } else {
          detail_ = null;
          detailBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public util.errors.MessageOuterClass.Message.Builder getDetailBuilder() {
        
        onChanged();
        return getDetailFieldBuilder().getBuilder();
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder() {
        if (detailBuilder_ != null) {
          return detailBuilder_.getMessageOrBuilder();
        } else {
          return detail_ == null ?
              util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
        }
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder> 
          getDetailFieldBuilder() {
        if (detailBuilder_ == null) {
          detailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder>(
                  getDetail(),
                  getParentForChildren(),
                  isClean());
          detail_ = null;
        }
        return detailBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:util.errors.Error)
    }

    // @@protoc_insertion_point(class_scope:util.errors.Error)
    private static final util.errors.ErrorOuterClass.Error DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new util.errors.ErrorOuterClass.Error();
    }

    public static util.errors.ErrorOuterClass.Error getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Error>
        PARSER = new com.google.protobuf.AbstractParser<Error>() {
      @java.lang.Override
      public Error parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Error(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Error> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Error> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public util.errors.ErrorOuterClass.Error getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WarningOrBuilder extends
      // @@protoc_insertion_point(interface_extends:util.errors.Warning)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The code.
     */
    util.errors.ErrorOuterClass.ErrorCode getCode();

    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return Whether the detail field is set.
     */
    boolean hasDetail();
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return The detail.
     */
    util.errors.MessageOuterClass.Message getDetail();
    /**
     * <code>.util.errors.Message detail = 2;</code>
     */
    util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder();
  }
  /**
   * <pre>
   *Warnings can have error codes, if it is useful in categorizing the severity of the warning.
   *For example a warning may be thrown if 2 securities are created with the same identifier.
   *Another example may be usage of a deprecated API.
   * </pre>
   *
   * Protobuf type {@code util.errors.Warning}
   */
  public static final class Warning extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:util.errors.Warning)
      WarningOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Warning.newBuilder() to construct.
    private Warning(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Warning() {
      code_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Warning();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Warning(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              util.errors.MessageOuterClass.Message.Builder subBuilder = null;
              if (detail_ != null) {
                subBuilder = detail_.toBuilder();
              }
              detail_ = input.readMessage(util.errors.MessageOuterClass.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(detail_);
                detail_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return util.errors.ErrorOuterClass.internal_static_util_errors_Warning_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return util.errors.ErrorOuterClass.internal_static_util_errors_Warning_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              util.errors.ErrorOuterClass.Warning.class, util.errors.ErrorOuterClass.Warning.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.util.errors.ErrorCode code = 1;</code>
     * @return The code.
     */
    @java.lang.Override public util.errors.ErrorOuterClass.ErrorCode getCode() {
      @SuppressWarnings("deprecation")
      util.errors.ErrorOuterClass.ErrorCode result = util.errors.ErrorOuterClass.ErrorCode.valueOf(code_);
      return result == null ? util.errors.ErrorOuterClass.ErrorCode.UNRECOGNIZED : result;
    }

    public static final int DETAIL_FIELD_NUMBER = 2;
    private util.errors.MessageOuterClass.Message detail_;
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return Whether the detail field is set.
     */
    @java.lang.Override
    public boolean hasDetail() {
      return detail_ != null;
    }
    /**
     * <code>.util.errors.Message detail = 2;</code>
     * @return The detail.
     */
    @java.lang.Override
    public util.errors.MessageOuterClass.Message getDetail() {
      return detail_ == null ? util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
    }
    /**
     * <code>.util.errors.Message detail = 2;</code>
     */
    @java.lang.Override
    public util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder() {
      return getDetail();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != util.errors.ErrorOuterClass.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (detail_ != null) {
        output.writeMessage(2, getDetail());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != util.errors.ErrorOuterClass.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (detail_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDetail());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof util.errors.ErrorOuterClass.Warning)) {
        return super.equals(obj);
      }
      util.errors.ErrorOuterClass.Warning other = (util.errors.ErrorOuterClass.Warning) obj;

      if (code_ != other.code_) return false;
      if (hasDetail() != other.hasDetail()) return false;
      if (hasDetail()) {
        if (!getDetail()
            .equals(other.getDetail())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      if (hasDetail()) {
        hash = (37 * hash) + DETAIL_FIELD_NUMBER;
        hash = (53 * hash) + getDetail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static util.errors.ErrorOuterClass.Warning parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Warning parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Warning parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static util.errors.ErrorOuterClass.Warning parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(util.errors.ErrorOuterClass.Warning prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Warnings can have error codes, if it is useful in categorizing the severity of the warning.
     *For example a warning may be thrown if 2 securities are created with the same identifier.
     *Another example may be usage of a deprecated API.
     * </pre>
     *
     * Protobuf type {@code util.errors.Warning}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:util.errors.Warning)
        util.errors.ErrorOuterClass.WarningOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Warning_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Warning_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                util.errors.ErrorOuterClass.Warning.class, util.errors.ErrorOuterClass.Warning.Builder.class);
      }

      // Construct using util.errors.ErrorOuterClass.Warning.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        if (detailBuilder_ == null) {
          detail_ = null;
        } else {
          detail_ = null;
          detailBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return util.errors.ErrorOuterClass.internal_static_util_errors_Warning_descriptor;
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Warning getDefaultInstanceForType() {
        return util.errors.ErrorOuterClass.Warning.getDefaultInstance();
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Warning build() {
        util.errors.ErrorOuterClass.Warning result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public util.errors.ErrorOuterClass.Warning buildPartial() {
        util.errors.ErrorOuterClass.Warning result = new util.errors.ErrorOuterClass.Warning(this);
        result.code_ = code_;
        if (detailBuilder_ == null) {
          result.detail_ = detail_;
        } else {
          result.detail_ = detailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof util.errors.ErrorOuterClass.Warning) {
          return mergeFrom((util.errors.ErrorOuterClass.Warning)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(util.errors.ErrorOuterClass.Warning other) {
        if (other == util.errors.ErrorOuterClass.Warning.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (other.hasDetail()) {
          mergeDetail(other.getDetail());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        util.errors.ErrorOuterClass.Warning parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (util.errors.ErrorOuterClass.Warning) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public util.errors.ErrorOuterClass.ErrorCode getCode() {
        @SuppressWarnings("deprecation")
        util.errors.ErrorOuterClass.ErrorCode result = util.errors.ErrorOuterClass.ErrorCode.valueOf(code_);
        return result == null ? util.errors.ErrorOuterClass.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(util.errors.ErrorOuterClass.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.util.errors.ErrorCode code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private util.errors.MessageOuterClass.Message detail_;
      private com.google.protobuf.SingleFieldBuilderV3<
          util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder> detailBuilder_;
      /**
       * <code>.util.errors.Message detail = 2;</code>
       * @return Whether the detail field is set.
       */
      public boolean hasDetail() {
        return detailBuilder_ != null || detail_ != null;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       * @return The detail.
       */
      public util.errors.MessageOuterClass.Message getDetail() {
        if (detailBuilder_ == null) {
          return detail_ == null ? util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
        } else {
          return detailBuilder_.getMessage();
        }
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder setDetail(util.errors.MessageOuterClass.Message value) {
        if (detailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detail_ = value;
          onChanged();
        } else {
          detailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder setDetail(
          util.errors.MessageOuterClass.Message.Builder builderForValue) {
        if (detailBuilder_ == null) {
          detail_ = builderForValue.build();
          onChanged();
        } else {
          detailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder mergeDetail(util.errors.MessageOuterClass.Message value) {
        if (detailBuilder_ == null) {
          if (detail_ != null) {
            detail_ =
              util.errors.MessageOuterClass.Message.newBuilder(detail_).mergeFrom(value).buildPartial();
          } else {
            detail_ = value;
          }
          onChanged();
        } else {
          detailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public Builder clearDetail() {
        if (detailBuilder_ == null) {
          detail_ = null;
          onChanged();
        } else {
          detail_ = null;
          detailBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public util.errors.MessageOuterClass.Message.Builder getDetailBuilder() {
        
        onChanged();
        return getDetailFieldBuilder().getBuilder();
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      public util.errors.MessageOuterClass.MessageOrBuilder getDetailOrBuilder() {
        if (detailBuilder_ != null) {
          return detailBuilder_.getMessageOrBuilder();
        } else {
          return detail_ == null ?
              util.errors.MessageOuterClass.Message.getDefaultInstance() : detail_;
        }
      }
      /**
       * <code>.util.errors.Message detail = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder> 
          getDetailFieldBuilder() {
        if (detailBuilder_ == null) {
          detailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              util.errors.MessageOuterClass.Message, util.errors.MessageOuterClass.Message.Builder, util.errors.MessageOuterClass.MessageOrBuilder>(
                  getDetail(),
                  getParentForChildren(),
                  isClean());
          detail_ = null;
        }
        return detailBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:util.errors.Warning)
    }

    // @@protoc_insertion_point(class_scope:util.errors.Warning)
    private static final util.errors.ErrorOuterClass.Warning DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new util.errors.ErrorOuterClass.Warning();
    }

    public static util.errors.ErrorOuterClass.Warning getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Warning>
        PARSER = new com.google.protobuf.AbstractParser<Warning>() {
      @java.lang.Override
      public Warning parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Warning(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Warning> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Warning> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public util.errors.ErrorOuterClass.Warning getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_util_errors_Error_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_util_errors_Error_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_util_errors_Warning_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_util_errors_Warning_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n requests/util/errors/error.proto\022\013util" +
      ".errors\032\"requests/util/errors/message.pr" +
      "oto\"S\n\005Error\022$\n\004code\030\001 \001(\0162\026.util.errors" +
      ".ErrorCode\022$\n\006detail\030\002 \001(\0132\024.util.errors" +
      ".Message\"U\n\007Warning\022$\n\004code\030\001 \001(\0162\026.util" +
      ".errors.ErrorCode\022$\n\006detail\030\002 \001(\0132\024.util" +
      ".errors.Message*+\n\tErrorCode\022\021\n\rUNKNOWN_" +
      "ERROR\020\000\022\013\n\007WARNING\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          util.errors.MessageOuterClass.getDescriptor(),
        });
    internal_static_util_errors_Error_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_util_errors_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_util_errors_Error_descriptor,
        new java.lang.String[] { "Code", "Detail", });
    internal_static_util_errors_Warning_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_util_errors_Warning_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_util_errors_Warning_descriptor,
        new java.lang.String[] { "Code", "Detail", });
    util.errors.MessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
