# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/price/price.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.util import decimal_value_pb2 as models_dot_util_dot_decimal__value__pb2
from models.util import local_timestamp_pb2 as models_dot_util_dot_local__timestamp__pb2
from models.util import uuid_pb2 as models_dot_util_dot_uuid__pb2
from models.security import security_pb2 as models_dot_security_dot_security__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18models/price/price.proto\x12\x05price\x1a\x1fmodels/util/decimal_value.proto\x1a!models/util/local_timestamp.proto\x1a\x16models/util/uuid.proto\x1a\x1emodels/security/security.proto\"\xe0\x01\n\nPriceProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1d\n\x04uuid\x18\x05 \x01(\x0b\x32\x0f.util.UUIDProto\x12(\n\x05\x61s_of\x18\x06 \x01(\x0b\x32\x19.util.LocalTimestampProto\x12\x0f\n\x07is_link\x18\x07 \x01(\x08\x12&\n\x05price\x18\n \x01(\x0b\x32\x17.util.DecimalValueProto\x12)\n\x08security\x18\x0b \x01(\x0b\x32\x17.security.SecurityProtoB$\n\x13\x63ommon.models.priceB\x0bPriceProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.price.price_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023common.models.priceB\013PriceProtosP\001'
  _PRICEPROTO._serialized_start=160
  _PRICEPROTO._serialized_end=384
# @@protoc_insertion_point(module_scope)
