# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/util/lock/lock_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.util.lock import node_state_pb2 as models_dot_util_dot_lock_dot_node__state__pb2
from requests.util import operation_pb2 as requests_dot_util_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%requests/util/lock/lock_request.proto\x12\tutil.lock\x1a!models/util/lock/node_state.proto\x1a\x1drequests/util/operation.proto\"\xa1\x01\n\x10LockRequestProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x37\n\x0eoperation_type\x18\n \x01(\x0e\x32\x1f.util.RequestOperationTypeProto\x12-\n\nnode_state\x18\x0b \x01(\x0b\x32\x19.util.lock.NodeStateProtoB*\n\x13\x63ommon.request.lockB\x11LockRequestProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.util.lock.lock_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023common.request.lockB\021LockRequestProtosP\001'
  _LOCKREQUESTPROTO._serialized_start=119
  _LOCKREQUESTPROTO._serialized_end=280
# @@protoc_insertion_point(module_scope)
