# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/portfolio/query_portfolio_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models.util import uuid_pb2 as models_dot_util_dot_uuid__pb2
from models.position import position_filter_pb2 as models_dot_position_dot_position__filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0requests/portfolio/query_portfolio_request.proto\x12\tportfolio\x1a\x16models/util/uuid.proto\x1a%models/position/position_filter.proto\"\xa2\x01\n\x1aQueryPortfolioRequestProto\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1e\n\x05uuids\x18\x15 \x03(\x0b\x32\x0f.util.UUIDProto\x12=\n\x16search_portfolio_input\x18\x16 \x01(\x0b\x32\x1d.position.PositionFilterProtoB/\n\x0e\x63ommon.requestB\x1bQueryPortfolioRequestProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.portfolio.query_portfolio_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016common.requestB\033QueryPortfolioRequestProtosP\001'
  _QUERYPORTFOLIOREQUESTPROTO._serialized_start=127
  _QUERYPORTFOLIOREQUESTPROTO._serialized_end=289
# @@protoc_insertion_point(module_scope)
