// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/models/security/coupon_type.proto

package common.model.protos;

public final class CouponTypeProtos {
  private CouponTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(protos/models/security/coupon_type.pro" +
      "to\022\010security*J\n\017CouponTypeProto\022\027\n\023UNKNO" +
      "WN_COUPON_TYPE\020\000\022\t\n\005FIXED\020\001\022\t\n\005FLOAT\020\002\022\010" +
      "\n\004ZERO\020\003B)\n\023common.model.protosB\020CouponT" +
      "ypeProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
