name: Deploy to AWS
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    # working-directory: ledger-models-python

jobs:
  publish-website-to-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install botocore
        pip install paramiko
        pip install fintekkers-devops-scripts
    - name: Setup server keypair
      run: | 
        mkdir ~/.aws
        echo -n $AWS_SERVER_KEYPAIR_BASE64 | base64 --decode > ~/.aws/fintekkers-test-ec2.pem
      env:
        AWS_SERVER_KEYPAIR_BASE64: ${{ secrets.AWS_SERVER_KEYPAIR_BASE64 }}   
    - name: Run the script
      run: python build_deploy.py
    - name: Delete server keypair
      run: | 
        mkdir ~/.aws
        rm -f ~/.aws/fintekkers-test-ec2.pem
